# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@babel/code-frame@7.29.7" = fetchurl {
    url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.29.7.tgz";
    hash = "sha512-Aup7aUOfpbAUg2ROOJN6Iw5f9DMBlzu0mIkm/malLQFN/YQgO48wCj0Kxa3sEHJvPVFg7siR+qRInwXd2qhQKw==";
  };
  "@babel/helper-validator-identifier@7.29.7" = fetchurl {
    url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.29.7.tgz";
    hash = "sha512-qehxGkRj55h/ff8EMaJ+cYhyaKlHIxqYDn682wQD7RNp9UujOQsHog2uS0r2vzr4pW+sXf90NeeayjcNaX3fFg==";
  };
  "@babel/runtime@7.29.7" = fetchurl {
    url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.7.tgz";
    hash = "sha512-Nq8OhGWiZIZGV6hLHoyAKLLcJihP/xFeBMGJoUrxTX2psI8dCifzLhZISFb+VWS3wFMRDmCGw5R+dOySCqPLhw==";
  };
  "@changesets/apply-release-plan@7.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/apply-release-plan/-/apply-release-plan-7.1.1.tgz";
    hash = "sha512-9qPCm/rLx/xoOFXIHGB229+4GOL76S4MC+7tyOuTsR6+1jYlfFDQORdvwR5hDA6y4FL2BPt3qpbcQIS+dW85LA==";
  };
  "@changesets/assemble-release-plan@6.0.10" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/assemble-release-plan/-/assemble-release-plan-6.0.10.tgz";
    hash = "sha512-rSDcqdJ9KbVyjpBIuCidhvZNIiVt1XaIYp73ycVQRIA5n/j6wQaEk0ChRLMUQ1vkxZe51PTQ9OIhbg6HQMW45A==";
  };
  "@changesets/changelog-git@0.2.1" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/changelog-git/-/changelog-git-0.2.1.tgz";
    hash = "sha512-x/xEleCFLH28c3bQeQIyeZf8lFXyDFVn1SgcBiR2Tw/r4IAWlk1fzxCEZ6NxQAjF2Nwtczoen3OA2qR+UawQ8Q==";
  };
  "@changesets/cli@2.31.0" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/cli/-/cli-2.31.0.tgz";
    hash = "sha512-AhI4enNTgHu2IZr6K4WZyf0EPch4XVMn1yOMFmCD9gsfBGqMYaHXls5HyDv6/CL5axVQABz68eG30eCtbr2wFg==";
  };
  "@changesets/config@3.1.4" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/config/-/config-3.1.4.tgz";
    hash = "sha512-pf0bvD/v6WI2cRlZ6hzpjtZdSlXDXMAJ+Iz7xfFzV4ZxJ8OGGAON+1qYc99ZPrijnt4xp3VGG7eNvAOGS24V1Q==";
  };
  "@changesets/errors@0.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/errors/-/errors-0.2.0.tgz";
    hash = "sha512-6BLOQUscTpZeGljvyQXlWOItQyU71kCdGz7Pi8H8zdw6BI0g3m43iL4xKUVPWtG+qrrL9DTjpdn8eYuCQSRpow==";
  };
  "@changesets/get-dependents-graph@2.1.4" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/get-dependents-graph/-/get-dependents-graph-2.1.4.tgz";
    hash = "sha512-ZsS00x6WvmHq3sQv8oCMwL0f/z3wbXCVuSVTJwCnnmbC/iBdNJGFx1EcbMG4PC6sXRyH69liM4A2WKXzn/kRPg==";
  };
  "@changesets/get-release-plan@4.0.16" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/get-release-plan/-/get-release-plan-4.0.16.tgz";
    hash = "sha512-2K5Om6CrMPm45rtvckfzWo7e9jOVCKLCnXia5eUPaURH7/LWzri7pK1TycdzAuAtehLkW7VPbWLCSExTHmiI6g==";
  };
  "@changesets/get-version-range-type@0.4.0" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/get-version-range-type/-/get-version-range-type-0.4.0.tgz";
    hash = "sha512-hwawtob9DryoGTpixy1D3ZXbGgJu1Rhr+ySH2PvTLHvkZuQ7sRT4oQwMh0hbqZH1weAooedEjRsbrWcGLCeyVQ==";
  };
  "@changesets/git@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/git/-/git-3.0.4.tgz";
    hash = "sha512-BXANzRFkX+XcC1q/d27NKvlJ1yf7PSAgi8JG6dt8EfbHFHi4neau7mufcSca5zRhwOL8j9s6EqsxmT+s+/E6Sw==";
  };
  "@changesets/logger@0.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/logger/-/logger-0.1.1.tgz";
    hash = "sha512-OQtR36ZlnuTxKqoW4Sv6x5YIhOmClRd5pWsjZsddYxpWs517R0HkyiefQPIytCVh4ZcC5x9XaG8KTdd5iRQUfg==";
  };
  "@changesets/parse@0.4.3" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/parse/-/parse-0.4.3.tgz";
    hash = "sha512-ZDmNc53+dXdWEv7fqIUSgRQOLYoUom5Z40gmLgmATmYR9NbL6FJJHwakcCpzaeCy+1D0m0n7mT4jj2B/MQPl7A==";
  };
  "@changesets/pre@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/pre/-/pre-2.0.2.tgz";
    hash = "sha512-HaL/gEyFVvkf9KFg6484wR9s0qjAXlZ8qWPDkTyKF6+zqjBe/I2mygg3MbpZ++hdi0ToqNUF8cjj7fBy0dg8Ug==";
  };
  "@changesets/read@0.6.7" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/read/-/read-0.6.7.tgz";
    hash = "sha512-D1G4AUYGrBEk8vj8MGwf75k9GpN6XL3wg8i42P2jZZwFLXnlr2Pn7r9yuQNbaMCarP7ZQWNJbV6XLeysAIMhTA==";
  };
  "@changesets/should-skip-package@0.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/should-skip-package/-/should-skip-package-0.1.2.tgz";
    hash = "sha512-qAK/WrqWLNCP22UDdBTMPH5f41elVDlsNyat180A33dWxuUDyNpg6fPi/FyTZwRriVjg0L8gnjJn2F9XAoF0qw==";
  };
  "@changesets/types@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/types/-/types-4.1.0.tgz";
    hash = "sha512-LDQvVDv5Kb50ny2s25Fhm3d9QSZimsoUGBsUioj6MC3qbMUCuC8GPIvk/M6IvXx3lYhAs0lwWUQLb+VIEUCECw==";
  };
  "@changesets/types@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/types/-/types-6.1.0.tgz";
    hash = "sha512-rKQcJ+o1nKNgeoYRHKOS07tAMNd3YSN0uHaJOZYjBAgxfV7TUE7JE+z4BzZdQwb5hKaYbayKN5KrYV7ODb2rAA==";
  };
  "@changesets/write@0.4.0" = fetchurl {
    url = "https://registry.npmjs.org/@changesets/write/-/write-0.4.0.tgz";
    hash = "sha512-CdTLvIOPiCNuH71pyDu3rA+Q0n65cmAbXnwWH84rKGiFumFzkmHNT8KHTMEchcxN+Kl8I54xGUhJ7l3E7X396Q==";
  };
  "@commitlint/cli@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/cli/-/cli-21.0.2.tgz";
    hash = "sha512-YMmfLbqBg+ZRvvmPhc+cilSQFrh/AgzVgCT1U/OifmUZEwPbvCtA8rN//YNaF9d5eoZphxVMGYtmwA2QgQORgg==";
  };
  "@commitlint/config-conventional@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/config-conventional/-/config-conventional-21.0.2.tgz";
    hash = "sha512-P/ZRhryQmkj0Z0dY9FOoRwe3xkwJyyAdtXwt01NT2kuZttcG2CNYp1q5Ci3u+nDT2jcbJRw2kt13Czl1qKNPfg==";
  };
  "@commitlint/config-validator@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/config-validator/-/config-validator-21.0.1.tgz";
    hash = "sha512-Zd2UFdndeMMaW2O96HK0tdfT4gOImUvidMpAd/pws2zZ4m1nrAZ/9b/v2JYuE8fs86GpXv9F7LNaIuCIWhY+pA==";
  };
  "@commitlint/ensure@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/ensure/-/ensure-21.0.1.tgz";
    hash = "sha512-jJ1037967wU7YN/xkv+iRlOBlmaOXPhPO5KQSqya6GyXzBlwuLzELBFao16DVg9dZyqmNrhewzwZ3SAibetHBQ==";
  };
  "@commitlint/execute-rule@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/execute-rule/-/execute-rule-21.0.1.tgz";
    hash = "sha512-RifH+FmImozKBE6mozhF4K3r2RRKP7SMi/Q/zLCmExtp5e05lhHOUYqGBlFBAGNHaZxU/WYw1XuugYK9jQzqnA==";
  };
  "@commitlint/format@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/format/-/format-21.0.1.tgz";
    hash = "sha512-ksmG2+cHGtuDPQQbhBbC4unwm444+6TiPw0d1bKf67hntgZqZ8E0g1MuYKUuyT5IH4IMmXZhKq22/Z3jBvtQIw==";
  };
  "@commitlint/is-ignored@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/is-ignored/-/is-ignored-21.0.2.tgz";
    hash = "sha512-H5z4t8PC9tUsmZ/o+EptM3Nq8sTFtskAShdcqxCoyzklW5eaVT5xbrDAET2uypzir9Vsj4ZZmBtyKjYe2XqgeQ==";
  };
  "@commitlint/lint@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/lint/-/lint-21.0.2.tgz";
    hash = "sha512-PnUmLYGeGLfW8oVatR9KpNxSHYAnJOEWlMZzfdeFOUq6WUrFx1fGQaWCWJqMoIll/xPM+GdfJV+tKHZVHhl0Fg==";
  };
  "@commitlint/load@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/load/-/load-21.0.2.tgz";
    hash = "sha512-lwUE70hN0/qE/ZRROhbaX65ly/FF12DrqfReLCESo37M0OQCFAf2jRS+2tSCSORq+bm4Kdju7qNDj46uc1QzTA==";
  };
  "@commitlint/message@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/message/-/message-21.0.2.tgz";
    hash = "sha512-5n4aqHGD/FNnom/D5L8i7cYtV+xjuXcBL832C3w9VglEsZzIsoHpJsvxzJ7cgiOsOdc/2jU4t5+7qMHh7GBX3g==";
  };
  "@commitlint/parse@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/parse/-/parse-21.0.2.tgz";
    hash = "sha512-QVZJhGHTm+oiuWyEKOCTQ0ZM3mfJ0eGWFeHuj7WzSKEth+UukcCHac9GD8pgdFlg/qGkFWOtyaNd1T8REgagaw==";
  };
  "@commitlint/read@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/read/-/read-21.0.2.tgz";
    hash = "sha512-BtsrnLVycSSKf4Q0gMch4giCj5NNlmcbhc8ra5vONgGtP2IjRDo33bEFtr5Pm+2N+5fXGWb2MksWPrspPfdhdw==";
  };
  "@commitlint/resolve-extends@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/resolve-extends/-/resolve-extends-21.0.1.tgz";
    hash = "sha512-0DhjYWL6uYrY16Efa032fYk3woGJDU4AGWiG1XXltT9AMUNYKyb5cIZU2ivbaMZ3+kKFqUjikD2cjh66Sbh/Sg==";
  };
  "@commitlint/rules@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/rules/-/rules-21.0.2.tgz";
    hash = "sha512-k6tQ69Td7t2qUSIbik8D3TL1q3ZJpkEbV+yLogDzCRAdOxJm4ndhtBNREsLA1/puRfWvzS9eioF2w43WT+hHgQ==";
  };
  "@commitlint/to-lines@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/to-lines/-/to-lines-21.0.1.tgz";
    hash = "sha512-bd1BFII7p1EQZre9Kaj+kKaMFP3cFCdt21K7DItVux9XP5WjLgJ0/Uy1pJJh9aPwVJ6SKg62PxqlZaHI8hQAXw==";
  };
  "@commitlint/top-level@21.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/top-level/-/top-level-21.0.2.tgz";
    hash = "sha512-s9KKM+e+mXgFeIh4n7KmOGAVT3mkJ3Fp1bBYHIK5pjeUwlEMzp/tZfb5u0Poa680AsQTXMEMRxZi1vQ9m2X5ug==";
  };
  "@commitlint/types@21.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@commitlint/types/-/types-21.0.1.tgz";
    hash = "sha512-4u7w8jcoCUFWhjWnASYzZHAP34OqOtuFBN87nQmFvqda03YU0T6z+yB4w0gSAMpekiRqqGk5rt+qSlW+a2vSEg==";
  };
  "@conventional-changelog/git-client@2.7.0" = fetchurl {
    url = "https://registry.npmjs.org/@conventional-changelog/git-client/-/git-client-2.7.0.tgz";
    hash = "sha512-j7A8/LBEQ+3rugMzPXoKYzyUPpw/0CBQCyvtTR7Lmu4olG4yRC/Tfkq79Mr3yuPs0SUitlO2HwGP3gitMJnRFw==";
  };
  "@inquirer/external-editor@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/@inquirer/external-editor/-/external-editor-1.0.3.tgz";
    hash = "sha512-RWbSrDiYmO4LbejWY7ttpxczuwQyZLBUyygsA9Nsv95hpzUWwnNTVQmAq3xuh7vNwCp07UTmE5i11XAEExx4RA==";
  };
  "@isaacs/fs-minipass@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@isaacs/fs-minipass/-/fs-minipass-4.0.1.tgz";
    hash = "sha512-wgm9Ehl2jpeqP3zw/7mo3kRHFp5MEDhqAdwy1fTGkHAwnkGOVsgpvQhL8B5n1qlb01jV3n/bI0ZfZp5lWA1k4w==";
  };
  "@j178/prek-android-arm64@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-android-arm64/-/prek-android-arm64-0.4.4.tgz";
    hash = "sha512-CEPNkXLl/VWxKz+S/02RCQDTEq/vF/prpPufPaIV89cqoVC2yRsaBML8tBtreLWjk1l4e04cQ/cs0ITI5PgSeA==";
  };
  "@j178/prek-darwin-arm64@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-darwin-arm64/-/prek-darwin-arm64-0.4.4.tgz";
    hash = "sha512-8hn7zzaa+BUU3PBpuEZQVXSGgfBwyDWiAPhoPum3IVdErZ1DufkvZPftvvjPkafl++nz7nmluXKs9bZx0WLumg==";
  };
  "@j178/prek-darwin-x64@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-darwin-x64/-/prek-darwin-x64-0.4.4.tgz";
    hash = "sha512-4lQo1KLK9cKzScUyfZ4Z37f2u99PjtFsizjVYSCxMfWe5K1VeeVbdutt2pqVaE8KDw/vNK5bwZ5Na3ODbE8N4A==";
  };
  "@j178/prek-linux-arm-gnueabihf@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-arm-gnueabihf/-/prek-linux-arm-gnueabihf-0.4.4.tgz";
    hash = "sha512-UGK+PqEtOTaDYLZR5BXMvuvcj4+3WQjCn4us/n6yM1sJcM4DvBqIx9OsA8+rK5/IKB2WHqHGrS5l+i105NeWNw==";
  };
  "@j178/prek-linux-arm-musleabihf@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-arm-musleabihf/-/prek-linux-arm-musleabihf-0.4.4.tgz";
    hash = "sha512-HAh6bL9tazfMd/DHbjbDEvepe83T8PDwJau4H4IQ6PViRTy+Xeye81c+vwU1rmVP7CZJO6LlhS/baBnP3XQLOg==";
  };
  "@j178/prek-linux-arm64-gnu@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-arm64-gnu/-/prek-linux-arm64-gnu-0.4.4.tgz";
    hash = "sha512-S+fznugJflcHVE22DVatqgrJCVipQdJyvrKYJxeKWB/hAjkWtyI7SPZMhF8QnBM8rMMybfl7CbzmQdWHJz2cnw==";
  };
  "@j178/prek-linux-arm64-musl@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-arm64-musl/-/prek-linux-arm64-musl-0.4.4.tgz";
    hash = "sha512-++Mv6PtnSwk2S7f9lhmPhY/+f7ePfbhAu1FuoCzJ03xvXJooDPL+nK1ybOf+UMYgctMIslLkEdUNCBt2eFoC5g==";
  };
  "@j178/prek-linux-armv7-musleabihf@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-armv7-musleabihf/-/prek-linux-armv7-musleabihf-0.4.4.tgz";
    hash = "sha512-x5c4jMnaPMhsBVhm192aazu5A0itPFJTR5JWEdJ71Owq8aEc4Zg/OBCGSZgrl3bqMafRB7N5FmzHzSfn6wEgcg==";
  };
  "@j178/prek-linux-ia32-gnu@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-ia32-gnu/-/prek-linux-ia32-gnu-0.4.4.tgz";
    hash = "sha512-uAbUmLFGrJQYS9/SgVuUQ9iauupf0PM7Ylx8AiGhVLUIJ8HBfqUo3fghPrBM1ifAwbD7FJPyjy4FwxfQoiU4gg==";
  };
  "@j178/prek-linux-ia32-musl@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-ia32-musl/-/prek-linux-ia32-musl-0.4.4.tgz";
    hash = "sha512-jHn2AgEPmqVpiRJHS1DYw1SAA9I0S/aLfiC1k2VheyjpMMF3OQQm2Xo4/iyIgFBWI04uvcPzsl6nQU9KvVjMPA==";
  };
  "@j178/prek-linux-riscv64-gnu@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-riscv64-gnu/-/prek-linux-riscv64-gnu-0.4.4.tgz";
    hash = "sha512-PdrIjTZig3oCHJcINIQ8RL5WR9ZQYxecK/ImMfy45MK4jEdZsjgtW9f/6u3AM0C0m6daVkpLxUOMLE/JQUYl/w==";
  };
  "@j178/prek-linux-s390x-gnu@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-s390x-gnu/-/prek-linux-s390x-gnu-0.4.4.tgz";
    hash = "sha512-O7GPZBzQLV5/Fdh6sfuCh6f0XF/i+8sQ+fxVvn5bRUryQiBBFxQ0LpcFxfKLrAj02iMhtOIlhLpYAgKum5YUZQ==";
  };
  "@j178/prek-linux-x64-gnu@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-x64-gnu/-/prek-linux-x64-gnu-0.4.4.tgz";
    hash = "sha512-jXs3r5BEnquoK+A8rb6jjxaivErG/e3LCl6LGzsLZ2kHvco1RwzWPpNrsQSmqyIbzfeWgyOrGivZ/xKoOjaEvg==";
  };
  "@j178/prek-linux-x64-musl@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-linux-x64-musl/-/prek-linux-x64-musl-0.4.4.tgz";
    hash = "sha512-+G/c7NwInkIOi3M+/fBREsbnq9ZpQ/LmLAC6DEzEjfdOFVOSlqn64WmRb3f79ZpN1IMfRU8PZdV7OYeHsIVg7g==";
  };
  "@j178/prek-win32-arm64-msvc@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-win32-arm64-msvc/-/prek-win32-arm64-msvc-0.4.4.tgz";
    hash = "sha512-H4gajhrKURmYgOEtmQN8V0U9nrWag8u9l9PKHh/sTrOva82NgtZgVSuRblszhmx2PAX2m/3I3Cdf/PCZs7InMA==";
  };
  "@j178/prek-win32-ia32-msvc@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-win32-ia32-msvc/-/prek-win32-ia32-msvc-0.4.4.tgz";
    hash = "sha512-kfq2IY4/3fjXWCdwIPP1X79aRssW29XTwhH6aXGhyRBbw5RIOw/OljrPkK7xQNQ/Jp/ri+ZBn1aeG8NuaQixiw==";
  };
  "@j178/prek-win32-x64-msvc@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek-win32-x64-msvc/-/prek-win32-x64-msvc-0.4.4.tgz";
    hash = "sha512-e/PtmjY+T2roRD1VjOxgkRXLadqxs477BwY+Oq9GSxUwSdA0J03CELWGJUg43Wq3pcuY6X9bIpMH7yfBaRDDBA==";
  };
  "@j178/prek@0.4.4" = fetchurl {
    url = "https://registry.npmjs.org/@j178/prek/-/prek-0.4.4.tgz";
    hash = "sha512-FFhheB9+EU8NSCCnHBannPiSuTERSU7m7VYZv/HJNxjScLrikmb6znukSIrbRhNxkk9G7w6HMBG26DsXNWsJhw==";
  };
  "@manypkg/find-root@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@manypkg/find-root/-/find-root-1.1.0.tgz";
    hash = "sha512-mki5uBvhHzO8kYYix/WRy2WX8S3B5wdVSc9D6KcU5lQNglP2yt58/VfLuAK49glRXChosY8ap2oJ1qgma3GUVA==";
  };
  "@manypkg/find-root@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@manypkg/find-root/-/find-root-3.1.0.tgz";
    hash = "sha512-BcSqCyKhBVZ5YkSzOiheMCV41kqAFptW6xGqYSTjkVTl9XQpr+pqHhwgGCOHQtjDCv7Is6EFyA14Sm5GVbVABA==";
  };
  "@manypkg/get-packages@1.1.3" = fetchurl {
    url = "https://registry.npmjs.org/@manypkg/get-packages/-/get-packages-1.1.3.tgz";
    hash = "sha512-fo+QhuU3qE/2TQMQmbVMqaQ6EWbMhi4ABWP+O4AM1NqPBuy0OrApV5LO6BrrgnhtAHS2NH6RrVk9OL181tTi8A==";
  };
  "@manypkg/get-packages@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@manypkg/get-packages/-/get-packages-3.1.0.tgz";
    hash = "sha512-0TbBVyvPrP7xGYBI/cP8UP+yl/z+HtbTttAD7FMAJgn/kXOTwh5/60TsqP9ZYY710forNfyV0N8P/IE/ujGZJg==";
  };
  "@manypkg/tools@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@manypkg/tools/-/tools-2.1.2.tgz";
    hash = "sha512-6QEf6yqFbETdwGITKq57aYoPfX/3K8XFNwsAlx0C1M7o8cb79sv1M3w+tWuWvIcSbNqrLF7OD7YpZMVVz335hQ==";
  };
  "@nodelib/fs.scandir@2.1.5" = fetchurl {
    url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
    hash = "sha512-vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
  };
  "@nodelib/fs.stat@2.0.5" = fetchurl {
    url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
    hash = "sha512-RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
  };
  "@nodelib/fs.walk@1.2.8" = fetchurl {
    url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
    hash = "sha512-oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
  };
  "@optique/core@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@optique/core/-/core-1.0.2.tgz";
    hash = "sha512-znsqMmjAdeOgSJzdJlpZpgAscojwQmeQYXzYnuEKllz5VCj6WyEkdzU4QuvJQtWQY3ve2taXwudEBRur0VHBOQ==";
  };
  "@optique/run@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@optique/run/-/run-1.0.2.tgz";
    hash = "sha512-0Wc+zC8SLGV8zXQX+pk+o0c6wE/ddx/36CHZ0toTh5lApsjruUuGhqbxvljerAAG5un1xQbOLxzksBVC6UPgSg==";
  };
  "@oxfmt/binding-android-arm-eabi@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-android-arm-eabi/-/binding-android-arm-eabi-0.54.0.tgz";
    hash = "sha512-NAtpl/SiaeU103e7/OmZw0MvUnsUUopW7hEm/ecegJg7YM0skQaA0IXEZoyTV6NUdiNPupdIUreRqUZTShbn/g==";
  };
  "@oxfmt/binding-android-arm64@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-android-arm64/-/binding-android-arm64-0.54.0.tgz";
    hash = "sha512-B4VZfBUlKK1rmMChsssNZbkZjE8+FzG3avMjGgMDwbGxXRoXkoeXiAZ+78Oa+eyDPHvDCiUb4zH/vmCOUSafLQ==";
  };
  "@oxfmt/binding-darwin-arm64@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-darwin-arm64/-/binding-darwin-arm64-0.54.0.tgz";
    hash = "sha512-i02vF75b+ePsQP3tHqSxVYI5S6b8X/xqdPu7/mDHXtpgXLTYXi3jJmfHU0j+dnZZDKaYTx/ioCK7QYJmtiJR2g==";
  };
  "@oxfmt/binding-darwin-x64@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-darwin-x64/-/binding-darwin-x64-0.54.0.tgz";
    hash = "sha512-8VMFvGvooXj7mswkbrhdVZ2/sgiDaBzWpkkbtO+qGDLV4EfJd67nQadHkQC0ZNbaWA9ajXfqI6i7PZLIeDzxEQ==";
  };
  "@oxfmt/binding-freebsd-x64@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-freebsd-x64/-/binding-freebsd-x64-0.54.0.tgz";
    hash = "sha512-0cRHnp43WN1Jrc5s0BdbdKgR1XirdvHy7TAFi3JEsoEVQVJxTXMbpVd76sxXlgRswNMDhVFSJw+y7Eb8mEavFQ==";
  };
  "@oxfmt/binding-linux-arm-gnueabihf@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-0.54.0.tgz";
    hash = "sha512-JyQAk3hK/OEtup7Rw6kZwfdzbKqTVD5jXXb8Xpfay29suwZyfBDMVW/bj4RqEPySYWc6zCp198pOluf8n5uYzg==";
  };
  "@oxfmt/binding-linux-arm-musleabihf@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-0.54.0.tgz";
    hash = "sha512-qnvLatTpM8vtvjOfcckBOzJjk+n6ce/wwpP8OFeUrD5aNLYcKyWAitwj+Rk3PK9jGanbZvKsJnv14JGQ6XqFdw==";
  };
  "@oxfmt/binding-linux-arm64-gnu@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.54.0.tgz";
    hash = "sha512-SMkhnCzIYZYDk9vw3W/80eeYKmrMpGF0Giuxt4HruFlCH7jEtnPeb3SdQKMfgYi/dgtaf+hZAb5XWPYnxqCQ3w==";
  };
  "@oxfmt/binding-linux-arm64-musl@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.54.0.tgz";
    hash = "sha512-QrwJlBFFKnxOd95TAaszpMbZBLzMoYMpGaQTZF8oibacnF5rv8l12IhILhQRPmksWiBqg0YSe2Mnl7ayeJAHSA==";
  };
  "@oxfmt/binding-linux-ppc64-gnu@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-0.54.0.tgz";
    hash = "sha512-WILatiol/TUHTlhod7R09+7Az/XlhKwmY1MHfLZNmewltPWNN/EwxP2rQSHahibZ/cB8gmckEBjBOByD+5bYsQ==";
  };
  "@oxfmt/binding-linux-riscv64-gnu@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-0.54.0.tgz";
    hash = "sha512-f05YMG4BH4G8S4ME6UM6fi1MnJ9094mrnvO5Pa4SJlMfWlUM+1/ZWMEF4NnjM7shZAvbHsHRuVYpUo0PHC4P9Q==";
  };
  "@oxfmt/binding-linux-riscv64-musl@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-0.54.0.tgz";
    hash = "sha512-UfL+2hj1ClNqcCRT9s8vBU4axDpjxgVxX96G+9DYAYjoc5b0u15CJtn2jgsi9iM+EbGNc5CW1HVRgwVu76UsSA==";
  };
  "@oxfmt/binding-linux-s390x-gnu@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-0.54.0.tgz";
    hash = "sha512-3/XZe931Hka+J6NjnaqJzYpsWWxDTuRdUdwSQHnOuJEgbC+SehIMFJS8hsEjV7LBhVSL2OCnRLvbVW8O97XIyw==";
  };
  "@oxfmt/binding-linux-x64-gnu@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.54.0.tgz";
    hash = "sha512-Ik93RlObtu43GbxApafayFjwYE06L6Xr08cSwpBPYbDrLp2ReZx0Jm1DqwRyYRnukUJy+rK2WaEvUQOxdytU9Q==";
  };
  "@oxfmt/binding-linux-x64-musl@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-linux-x64-musl/-/binding-linux-x64-musl-0.54.0.tgz";
    hash = "sha512-yZcakmPlD86CNymknd7KfW+FH+qfbqJH+i0h69CYfV1+KMoVeM9UED+8+TDVoU4haxI0NxY7RPCvRLy3Sqd2Qg==";
  };
  "@oxfmt/binding-openharmony-arm64@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-openharmony-arm64/-/binding-openharmony-arm64-0.54.0.tgz";
    hash = "sha512-GiVBZNnEZnKu00f1jTg49nomv187d0GQX+O+ocykoLeiaALuEO+swoTehHn9TehTfi7V8H0i0e/yvUjCqnwk1w==";
  };
  "@oxfmt/binding-win32-arm64-msvc@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-0.54.0.tgz";
    hash = "sha512-J0SSB8Z1Fre2sxRolYcW6Rl1RQmKdQ2hnHyq4YJrfBRiXTObLw4DXnIVraM/UyqGqwOi7yTrQA4VT7DPxlHVKA==";
  };
  "@oxfmt/binding-win32-ia32-msvc@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-0.54.0.tgz";
    hash = "sha512-O61UDVj8zz6yXJjkHPf05VaMLOXmEF8P5kf/N0W7AQMmd6bcQogl+KJc7rMutKTL524oE9iH32JXZClBFmEQIg==";
  };
  "@oxfmt/binding-win32-x64-msvc@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxfmt/binding-win32-x64-msvc/-/binding-win32-x64-msvc-0.54.0.tgz";
    hash = "sha512-1MDpqJPiFqxWtIHas8vkb1VZ7f7eKyTffAwmO8isxQYMaG1OFKsH666BWLeXQLO+IWNfiMssLD55hbR1lIPTqg==";
  };
  "@oxlint-tsgolint/darwin-arm64@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint-tsgolint/darwin-arm64/-/darwin-arm64-0.23.0.tgz";
    hash = "sha512-gOs9PVr2wEg4ox9z0aJo+RKhhImW86YL5N6yav8BK/rgPsIrwN/igSZ+pbRr723NFvUNKde9fgMhRA6JrXAOZw==";
  };
  "@oxlint-tsgolint/darwin-x64@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint-tsgolint/darwin-x64/-/darwin-x64-0.23.0.tgz";
    hash = "sha512-kjJ8B+7n4tB9VJdxS5A9GdJt6/bYpzbu4lXp2uO1S3sRmCB5gDEABlGoiePNApRWaW+xqL4b4xgiE727jSLhuA==";
  };
  "@oxlint-tsgolint/linux-arm64@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint-tsgolint/linux-arm64/-/linux-arm64-0.23.0.tgz";
    hash = "sha512-6dCZuKNu135seMXilkRk9SpCx6i1XgmiipYGalLij5WVRX6ZYS8c4xI7preN/zv9fCXhsQclTIMDu2Y/cytTjw==";
  };
  "@oxlint-tsgolint/linux-x64@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint-tsgolint/linux-x64/-/linux-x64-0.23.0.tgz";
    hash = "sha512-3bdilnyA7kmSTjK27rvjIjSxL5SIg3wt7vwNiRkouWB83ytssyKnuGvxSYJxgMEmFpSutzaBzcCUM2jDtPGcgA==";
  };
  "@oxlint-tsgolint/win32-arm64@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint-tsgolint/win32-arm64/-/win32-arm64-0.23.0.tgz";
    hash = "sha512-j+OEp44SVYiQ+ZD+uttsX7u6L9SvmbbQ77SO1pSFCcJlsVMeCk8qZsjhKfGKuT/jIA+ipOJMVs/+pqUfObBWNw==";
  };
  "@oxlint-tsgolint/win32-x64@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint-tsgolint/win32-x64/-/win32-x64-0.23.0.tgz";
    hash = "sha512-5MyjFuqf+g8OUPJBSGWHJtmoWnzFJYyOg4To9WMQshZYEWig/vtu7JtJ03VWnzHv9LJkAUeApY0gVCOywFR/iQ==";
  };
  "@oxlint/binding-android-arm-eabi@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-android-arm-eabi/-/binding-android-arm-eabi-1.69.0.tgz";
    hash = "sha512-DKQQbD5cZ/MYfDgDI7YGyGD9FSxABlsBsYFo5p26lloob543tP9+4N3guwdXIYJN+7HSZxLe8YJuwcOWw5qnHg==";
  };
  "@oxlint/binding-android-arm64@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-android-arm64/-/binding-android-arm64-1.69.0.tgz";
    hash = "sha512-lEhb+I5pr4inux+JFwfCa1HRq3Os7NirEFQ0H1I35SVEHPm6byX0Ah47xmRha3qi6LAkxUcxViL8o/9PivjzBg==";
  };
  "@oxlint/binding-darwin-arm64@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-darwin-arm64/-/binding-darwin-arm64-1.69.0.tgz";
    hash = "sha512-GY2YE8lOZW59BW1Ia1y+1gR0XyjrZRvVWHAr8LGeGhYHE0OQJ/7cRKXTkx1P+E9/6awEc3SX8a68SFTjh/E//A==";
  };
  "@oxlint/binding-darwin-x64@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-darwin-x64/-/binding-darwin-x64-1.69.0.tgz";
    hash = "sha512-ax1oZnOjHX3LB7myQyHEaQkDwfLb6str3/nSP6O7EVUviQGNkEGzGV0EqcBJWK+Ufwx0l4xPgyYayurvhAdl2Q==";
  };
  "@oxlint/binding-freebsd-x64@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-freebsd-x64/-/binding-freebsd-x64-1.69.0.tgz";
    hash = "sha512-kHWeHv4g2h8NY+mpCxzCtY4uerMJWTN/TSnNj1CPbakFpHEJ6cTya2wWV0pDSYWOJ2+0UiEbhn3AtXxHtsnKjg==";
  };
  "@oxlint/binding-linux-arm-gnueabihf@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.69.0.tgz";
    hash = "sha512-gq84vM1a1oEehXo27YCDzGVcxPsZDI1yswZwz2Da1/cbnWtrL16XZZnz0G/+gIU8edtHpfjxq5c+vWEHqJfWoQ==";
  };
  "@oxlint/binding-linux-arm-musleabihf@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-1.69.0.tgz";
    hash = "sha512-kIqEa98JQ0VRyrcncxA417m2AzasqTlD+FyVT1AksjvjkqQcvm7pBWYvoW3/mpyOP2XYvi5nSCCTIe6De1yu5g==";
  };
  "@oxlint/binding-linux-arm64-gnu@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.69.0.tgz";
    hash = "sha512-j+xYiXozxGWx2cpjCrwwGR4awTxPFsRv3JZrv23RCogEPMc4R7UqjHW47p/RG0aRlbWiROCJ8coUfCwy0dvzHA==";
  };
  "@oxlint/binding-linux-arm64-musl@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.69.0.tgz";
    hash = "sha512-xEPpNppTfN1l/nM7gYSf9iocscu/as+p/7vxkLeLEKnYU+09Dm+5V6IhDYDh+Uz6FajEupWwCLt5SOG0y1PCKg==";
  };
  "@oxlint/binding-linux-ppc64-gnu@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.69.0.tgz";
    hash = "sha512-Ug0+eU7HJBlek+SjklYH62IlOMirEJsdxpihH0kSqX0XdrDD4NdHpQc10fK1JC35yn6KrrcN+uYzlHD38XAf8Q==";
  };
  "@oxlint/binding-linux-riscv64-gnu@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-1.69.0.tgz";
    hash = "sha512-iEyI3GIg0l/s3G4qy2TlaaWKdzj4PJJStwtlocpDTC00PY9hZueotf6OKUj9+yfQh0lrpBW/pLMgTztbAHKJEg==";
  };
  "@oxlint/binding-linux-riscv64-musl@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-1.69.0.tgz";
    hash = "sha512-NjHjpiI4WIKSMwuoJSZi5VToPeoYOS1FR52HLIDG6lidMdqquusgtODb4iLk0+lb1q3Z0nv2/aPRcC/olmpQGg==";
  };
  "@oxlint/binding-linux-s390x-gnu@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.69.0.tgz";
    hash = "sha512-Ai/prDewoItkDXbp38gwGZi41DycZbUTZJ3UidwoHgQC0/DaqC2TGdtBTQLJ6hSD+SAxASzh8+/eSBPmxfOacA==";
  };
  "@oxlint/binding-linux-x64-gnu@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.69.0.tgz";
    hash = "sha512-Gt3KHgp46mRKz4sJeaASmKvD8ayXookRw07RMf+NowhEztGGDZ7VrXpoW96XuKJLjFukWizOFVNjmYb/u7caNQ==";
  };
  "@oxlint/binding-linux-x64-musl@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-linux-x64-musl/-/binding-linux-x64-musl-1.69.0.tgz";
    hash = "sha512-7tQhJ2+p/oHv1zcfnjYI7YVzC/7iBaVOfIvFYtxdJ5F45mWgEdrCyXZXZGfiLey5t/5JhOhsaMnnv1kAzckd7g==";
  };
  "@oxlint/binding-openharmony-arm64@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-openharmony-arm64/-/binding-openharmony-arm64-1.69.0.tgz";
    hash = "sha512-vmWz6TKp/3hfA4lksR0zHBv/6xuX1jhym6eqOjdH2DXsDDHZWcp2f0KG0VCAnlVbIrjk29G4wAWMXb/Hn1YobA==";
  };
  "@oxlint/binding-win32-arm64-msvc@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.69.0.tgz";
    hash = "sha512-9RExaLgmaw6IoIkU9cTpT71mLfI0xZ86iZH8x518LVsOkjquJMYqb9P7KpC8lgd1t0Dxs41p2pxynq4XR3Ttzw==";
  };
  "@oxlint/binding-win32-ia32-msvc@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-1.69.0.tgz";
    hash = "sha512-1907kRPF8/PrcIw1E7LMs9JbVrpgnt/MvFdss3an8oDkYNAACXzTntV3t3869ZZhMZxb2AzRGbz1pA/jdFatXA==";
  };
  "@oxlint/binding-win32-x64-msvc@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/@oxlint/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.69.0.tgz";
    hash = "sha512-w8SOXv3mT9Fi6jY8OXdXCfnvX/3KNLXGNr4HEz2TA7S4Mv/PYAOmpB8y/ge40mxvBMgGNaSaaDwZpAsQn7HtWA==";
  };
  "@simple-libs/child-process-utils@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@simple-libs/child-process-utils/-/child-process-utils-1.0.2.tgz";
    hash = "sha512-/4R8QKnd/8agJynkNdJmNw2MBxuFTRcNFnE5Sg/G+jkSsV8/UBgULMzhizWWW42p8L5H7flImV2ATi79Ove2Tw==";
  };
  "@simple-libs/stream-utils@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@simple-libs/stream-utils/-/stream-utils-1.2.0.tgz";
    hash = "sha512-KxXvfapcixpz6rVEB6HPjOUZT22yN6v0vI0urQSk1L8MlEWPDFCZkhw2xmkyoTGYeFw7tWTZd7e3lVzRZRN/EA==";
  };
  "@sindresorhus/merge-streams@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@sindresorhus/merge-streams/-/merge-streams-4.0.0.tgz";
    hash = "sha512-tlqY9xq5ukxTUZBmoOp+m61cqwQD5pHJtFY3Mn8CA8ps6yghLH/Hw8UPdqg4OLmFW3IFlcXnQNmo/dh8HzXYIQ==";
  };
  "@taplo/cli@0.7.0" = fetchurl {
    url = "https://registry.npmjs.org/@taplo/cli/-/cli-0.7.0.tgz";
    hash = "sha512-Ck3zFhQhIhi02Hl6T4ZmJsXdnJE+wXcJz5f8klxd4keRYgenMnip3JDPMGDRLbnC/2iGd8P0sBIQqI3KxfVjBg==";
  };
  "@turbo/darwin-64@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/@turbo/darwin-64/-/darwin-64-2.9.18.tgz";
    hash = "sha512-9f27peFu16ur8c0v9nUFUEyBnbKuuFsUTjHFWfmwGfzySBXbHwzU44QhZon6Mznz0cHsIr3984NQj/bVrnGSRw==";
  };
  "@turbo/darwin-arm64@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/@turbo/darwin-arm64/-/darwin-arm64-2.9.18.tgz";
    hash = "sha512-9A6TMRq/Ib+QnbhLlgkhOm+624wO4pzSQ/yQviQfWHOlFvaYxdnIAYmu2H6TS6y7kSVL0DvzNe04NbESTOzFVQ==";
  };
  "@turbo/linux-64@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/@turbo/linux-64/-/linux-64-2.9.18.tgz";
    hash = "sha512-zCdIDtz69AnbYh913elJRRoF3QY5aa2HNnf+4rAkc7bQ+tWujiDkCNV7stazOUPggaDvhKIf2Z87qHftTeXSkw==";
  };
  "@turbo/linux-arm64@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/@turbo/linux-arm64/-/linux-arm64-2.9.18.tgz";
    hash = "sha512-Va1kXI04naMgYwqv/5Dfa36dTDx8015U7oaQAjrXa45ua9OoFjSV4OmvkML4EmXvUclQHCiBRbY8bvd0jV7eAg==";
  };
  "@turbo/windows-64@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/@turbo/windows-64/-/windows-64-2.9.18.tgz";
    hash = "sha512-m0kDhZANxSNz9ck1ybogFscHabriAsp4eDFNrN/1H5WrgTF7b3VlcPZnhuO3v2+E2KnCbeAc+UUT10BZZHdDKw==";
  };
  "@turbo/windows-arm64@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/@turbo/windows-arm64/-/windows-arm64-2.9.18.tgz";
    hash = "sha512-nUdR8WqoomUys9iIQmG45TMiizJ+5BV8egSeLLZba/AWblyp3fVBcIH1kSE58OtK4g2YzbMJEth6Ttv9w5rqMA==";
  };
  "@types/debug@4.1.13" = fetchurl {
    url = "https://registry.npmjs.org/@types/debug/-/debug-4.1.13.tgz";
    hash = "sha512-KSVgmQmzMwPlmtljOomayoR89W4FynCAi3E8PPs7vmDVPe84hT+vGPKkJfThkmXs0x0jAaa9U8uW8bbfyS2fWw==";
  };
  "@types/katex@0.16.8" = fetchurl {
    url = "https://registry.npmjs.org/@types/katex/-/katex-0.16.8.tgz";
    hash = "sha512-trgaNyfU+Xh2Tc+ABIb44a5AYUpicB3uwirOioeOkNPPbmgRNtcWyDeeFRzjPZENO9Vq8gvVqfhaaXWLlevVwg==";
  };
  "@types/ms@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/ms/-/ms-2.1.0.tgz";
    hash = "sha512-GsCCIZDE/p3i96vtEqx+7dBUGXrc7zeSK3wwPHIaRThS+9OhWIXRqzs4d6k1SVU8g91DrNRWxWUGhp5KXQb2VA==";
  };
  "@types/node@12.20.55" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-12.20.55.tgz";
    hash = "sha512-J8xLz7q2OFulZ2cyGTLE1TbbZcjpno7FaN6zdJNrgAdrJ+DZzh/uFR6YrTb4C+nXakvud8Q4+rbhoIWlYQbUFQ==";
  };
  "@types/node@24.13.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-24.13.3.tgz";
    hash = "sha512-Dh8vAsV36ig5wa9OX4pXvMc9D3Veibfw2wix0CUwYODLD8nkj9UsLjASr49nPg+2eKzxhBV+v7L8pXvT4e639Q==";
  };
  "@types/node@25.6.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.6.1.tgz";
    hash = "sha512-coJCN8O1q4AGyyqCAUSP06P+SrMTu18BkEj3NVAK07q6QUneD2wzj3CLv9+yP+BMeZQlMvneXqqvDe3w+xcq7g==";
  };
  "@types/unist@2.0.11" = fetchurl {
    url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.11.tgz";
    hash = "sha512-CmBKiL6NNo/OqgmMn95Fk9Whlp2mtvIv+KNpQKN2F4SjvrEesubTRWGYSg+BnWZOnlCaSTU1sMpsBOzgbYhnsA==";
  };
  "@types/yauzl@3.3.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/yauzl/-/yauzl-3.3.0.tgz";
    hash = "sha512-7YJZZveDGYqCMt0PrN0sjZj9gT07xLqnHBimKwhWYTJ4lh5MxDGmaCaN4+6x1TOPt+dk3Ge8w9cO3uJXoy/qrA==";
  };
  "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-darwin-arm64/-/native-preview-darwin-arm64-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-wny2pgKjGbiZtnOIHVa3tXC1UfDqxNEFzyPGmiqybedG8hipG2Nfp0l5UxbaKCjkLacUpH/W5bP2hBOMVhCOzg==";
  };
  "@typescript/native-preview-darwin-x64@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-darwin-x64/-/native-preview-darwin-x64-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-Afc7M5zOwo+GpfcYwz5Z8HMB2tPVsui7nNIqEuuFB73MPdVqNn/Wmpe4tP4MRri0AtJnJknoHBaTJ/VDAp/Jhw==";
  };
  "@typescript/native-preview-linux-arm64@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-linux-arm64/-/native-preview-linux-arm64-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-iITBa2WjjTI5N9t5l7Z4KoOSI+2zBlhbvFzsD/f8qX8QoKjz/Y4DPyBDgezYi8nkqjjksbgSOJ3/ykzhwrB9cg==";
  };
  "@typescript/native-preview-linux-arm@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-linux-arm/-/native-preview-linux-arm-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-hJm/UOqZTr9FHmR7uNm8VGX4oKtfWk0Jem0zPeJFNC8ckGUfSBueyiEYMZB+XmRc1aG4x1E46y3CplP4CLHvGQ==";
  };
  "@typescript/native-preview-linux-x64@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-linux-x64/-/native-preview-linux-x64-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-du0dzi6y97Po5vDNdPJTyyijHCpaS22JLRnKZEJXBDaO9gCIymOv/5QQokFRuOlQm0bWl3i9PF4OVdGP6uAOQA==";
  };
  "@typescript/native-preview-win32-arm64@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-win32-arm64/-/native-preview-win32-arm64-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-SsAwfhyHJ1akgBc+99z4+hwdbHsdWaKB8EwCNIMA6JfSLMeUjffrYvxu+vfMyxVtOVOz7RrRXRoiDiu4a2sCtg==";
  };
  "@typescript/native-preview-win32-x64@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview-win32-x64/-/native-preview-win32-x64-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-DL4u27stv0fo71sVhOzHSwE+YMZsbBijVI+kg5dLDLilSH79WFTJ8RSQ46vJrCMt+Gjlv/JOZP1PuLJDfioYeQ==";
  };
  "@typescript/native-preview@7.0.0-dev.20260707.2" = fetchurl {
    url = "https://registry.npmjs.org/@typescript/native-preview/-/native-preview-7.0.0-dev.20260707.2.tgz";
    hash = "sha512-oUGp+Rep/hqMhPunyinsALUwSlzHINSxitifPiSaeqoKOKD2OlR9NE3TaPqwsl4NlGslsOSUXI1JotWQzpYCPg==";
  };
  "@wasm-fmt/shfmt@0.2.7" = fetchurl {
    url = "https://registry.npmjs.org/@wasm-fmt/shfmt/-/shfmt-0.2.7.tgz";
    hash = "sha512-bxmf5pXBHe3ujjc2iEoXqRXKgrQmR44jHLZ9G5BsKsb5moDWsuqsISs+88Ov9/SAI88caXYIsP02U4c4YDQpIQ==";
  };
  "@x2zod/build-inputs" = copyPathToStore ./packages/build-inputs;
  "@x2zod/cli" = copyPathToStore ./apps/cli;
  "@x2zod/code-quality-oxfmt" = copyPathToStore ./packages/code-quality-oxfmt;
  "@x2zod/code-quality-oxlint" = copyPathToStore ./packages/code-quality-oxlint;
  "@x2zod/config" = copyPathToStore ./packages/config;
  "@x2zod/core" = copyPathToStore ./packages/core;
  "@x2zod/eslint-plugins" = copyPathToStore ./packages/eslint-plugins;
  "@x2zod/input-json-schema" = copyPathToStore ./packages/input-json-schema;
  "@x2zod/tsconfig" = copyPathToStore ./packages/tsconfig;
  "ajv@8.20.0" = fetchurl {
    url = "https://registry.npmjs.org/ajv/-/ajv-8.20.0.tgz";
    hash = "sha512-Thbli+OlOj+iMPYFBVBfJ3OmCAnaSyNn4M1vz9T6Gka5Jt9ba/HIR56joy65tY6kx/FCF5VXNB819Y7/GUrBGA==";
  };
  "ansi-colors@4.1.3" = fetchurl {
    url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.3.tgz";
    hash = "sha512-/6w/C21Pm1A7aZitlI5Ni/2J6FFQN8i1Cvz3kHABAAbw93v/NlvKdVOqz7CCWz/3iv/JplRSEEZ83XION15ovw==";
  };
  "ansi-regex@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
    hash = "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
  };
  "ansi-regex@6.2.2" = fetchurl {
    url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.2.2.tgz";
    hash = "sha512-Bq3SmSpyFHaWjPk8If9yc6svM8c56dB5BAtW4Qbw5jHTwwXXcTLoRMkpDJp6VL0XzlWaCHTXrkFURMYmD0sLqg==";
  };
  "ansi-styles@6.2.3" = fetchurl {
    url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.3.tgz";
    hash = "sha512-4Dj6M28JB+oAH8kFkTLUo+a2jwOFkuqb3yucU0CANcRRUbxS0cP0nZYCGjcc3BNXwRIsUVmDGgzawme7zvJHvg==";
  };
  "argparse@1.0.10" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
    hash = "sha512-o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
  };
  "argparse@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
    hash = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
  };
  "array-ify@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/array-ify/-/array-ify-1.0.0.tgz";
    hash = "sha512-c5AMf34bKdvPhQ7tBGhqkgKNUzMr4WUs+WDtC2ZUGOUncbxKMTvqxYctiseW3+L4bA8ec+GcZ6/A/FW4m8ukng==";
  };
  "array-union@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/array-union/-/array-union-2.1.0.tgz";
    hash = "sha512-HGyxoOTYUyCM6stUe6EJgnd4EoewAI7zMdfqO+kGjnlZmBDz/cR5pf8r/cR4Wq60sL/p0IkcjUEEPwS3GFrIyw==";
  };
  "balanced-match@4.0.4" = fetchurl {
    url = "https://registry.npmjs.org/balanced-match/-/balanced-match-4.0.4.tgz";
    hash = "sha512-BLrgEcRTwX2o6gGxGOCNyMvGSp35YofuYzw9h1IMTRmKqttAZZVU67bdb9Pr2vUHA8+j3i2tJfjO6C6+4myGTA==";
  };
  "better-path-resolve@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/better-path-resolve/-/better-path-resolve-1.0.0.tgz";
    hash = "sha512-pbnl5XzGBdrFU/wT4jqmJVPn2B6UHPBOhzMQkY/SPUPB6QtUXtmBHBIwCbXJol93mOpGMnQyP/+BB19q04xj7g==";
  };
  "brace-expansion@5.0.6" = fetchurl {
    url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-5.0.6.tgz";
    hash = "sha512-kLpxurY4Z4r9sgMsyG0Z9uzsBlgiU/EFKhj/h91/8yHu0edo7XuixOIH3VcJ8kkxs6/jPzoI6U9Vj3WqbMQ94g==";
  };
  "braces@3.0.3" = fetchurl {
    url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
    hash = "sha512-yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
  };
  "c12@4.0.0-beta.5" = fetchurl {
    url = "https://registry.npmjs.org/c12/-/c12-4.0.0-beta.5.tgz";
    hash = "sha512-yWGCPCQGJeFq4R0mFg5HOhC3Rg+B0PCdM+ldXWUhughoGgeeq8/tjRmXh4/lmhKWyhf+KOFxB/JMXf0Yv1Fd5A==";
  };
  "callsites@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
    hash = "sha512-P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
  };
  "character-entities-legacy@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/character-entities-legacy/-/character-entities-legacy-3.0.0.tgz";
    hash = "sha512-RpPp0asT/6ufRm//AJVwpViZbGM/MkjQFxJccQRHmISF/22NBtsHqAWmL+/pmkPWoIUJdWyeVleTl1wydHATVQ==";
  };
  "character-entities@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/character-entities/-/character-entities-2.0.2.tgz";
    hash = "sha512-shx7oQ0Awen/BRIdkjkvz54PnEEI/EjwXDSIZp86/KKdbafHh1Df/RYGBhn4hbe2+uKC9FnT5UCEdyPz3ai9hQ==";
  };
  "character-reference-invalid@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/character-reference-invalid/-/character-reference-invalid-2.0.1.tgz";
    hash = "sha512-iBZ4F4wRbyORVsu0jPV7gXkOsGYjGHPmAyv+HiHG8gi5PtC9KI2j1+v8/tlibRvjoWX027ypmG/n0HtO5t7unw==";
  };
  "chardet@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/chardet/-/chardet-2.1.1.tgz";
    hash = "sha512-PsezH1rqdV9VvyNhxxOW32/d75r01NY7TQCmOqomRo15ZSOKbpTFVsfjghxo6JloQUCGnH4k1LGu0R4yCLlWQQ==";
  };
  "chokidar@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/chokidar/-/chokidar-5.0.0.tgz";
    hash = "sha512-TQMmc3w+5AxjpL8iIiwebF73dRDF4fBIieAqGn9RGCWaEVwQ6Fb2cGe31Yns0RRIzii5goJ1Y7xbMwo1TxMplw==";
  };
  "chownr@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/chownr/-/chownr-3.0.0.tgz";
    hash = "sha512-+IxzY9BZOQd/XuYPRmrvEVjF/nqj5kgT4kEq7VofrDoM1MxoRjEWkrCC3EtLi59TVawxTAn+orJwFQcrqEN1+g==";
  };
  "cliui@9.0.1" = fetchurl {
    url = "https://registry.npmjs.org/cliui/-/cliui-9.0.1.tgz";
    hash = "sha512-k7ndgKhwoQveBL+/1tqGJYNz097I7WOvwbmmU2AR5+magtbjPWQTS1C5vzGkBC8Ym8UWRzfKUzUUqFLypY4Q+w==";
  };
  "commander@8.3.0" = fetchurl {
    url = "https://registry.npmjs.org/commander/-/commander-8.3.0.tgz";
    hash = "sha512-OkTL9umf+He2DZkUq8f8J9of7yL6RJKI24dVITBmNfZBmri9zYZQrKkuXiKhyfPSu8tUhnVBB1iKXevvnlR4Ww==";
  };
  "compare-func@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/compare-func/-/compare-func-2.0.0.tgz";
    hash = "sha512-zHig5N+tPWARooBnb0Zx1MFcdfpyJrfTJ3Y5L+IFvUm8rM74hHz66z0gw0x4tijh5CorKkKUCnW82R2vmpeCRA==";
  };
  "confbox@0.2.4" = fetchurl {
    url = "https://registry.npmjs.org/confbox/-/confbox-0.2.4.tgz";
    hash = "sha512-ysOGlgTFbN2/Y6Cg3Iye8YKulHw+R2fNXHrgSmXISQdMnomY6eNDprVdW9R5xBguEqI954+S6709UyiO7B+6OQ==";
  };
  "conventional-changelog-angular@8.3.1" = fetchurl {
    url = "https://registry.npmjs.org/conventional-changelog-angular/-/conventional-changelog-angular-8.3.1.tgz";
    hash = "sha512-6gfI3otXK5Ph5DfCOI1dblr+kN3FAm5a97hYoQkqNZxOaYa5WKfXH+AnpsmS+iUH2mgVC2Cg2Qw9m5OKcmNrIg==";
  };
  "conventional-changelog-conventionalcommits@9.3.1" = fetchurl {
    url = "https://registry.npmjs.org/conventional-changelog-conventionalcommits/-/conventional-changelog-conventionalcommits-9.3.1.tgz";
    hash = "sha512-dTYtpIacRpcZgrvBYvBfArMmK2xvIpv2TaxM0/ZI5CBtNUzvF2x0t15HsbRABWprS6UPmvj+PzHVjSx4qAVKyw==";
  };
  "conventional-commits-parser@6.4.0" = fetchurl {
    url = "https://registry.npmjs.org/conventional-commits-parser/-/conventional-commits-parser-6.4.0.tgz";
    hash = "sha512-tvRg7FIBNlyPzjdG8wWRlPHQJJHI7DylhtRGeU9Lq+JuoPh5BKpPRX83ZdLrvXuOSu5Eo/e7SzOQhU4Hd2Miuw==";
  };
  "cosmiconfig-typescript-loader@6.3.0" = fetchurl {
    url = "https://registry.npmjs.org/cosmiconfig-typescript-loader/-/cosmiconfig-typescript-loader-6.3.0.tgz";
    hash = "sha512-Akr82WH1Wfqatyiqpj8HDkO2o2KmJRu1FhKfSNJP3K4IdXwHfEyL7MOb62i1AGQVLtIQM+iCE9CGOtrfhR+mmA==";
  };
  "cosmiconfig@9.0.1" = fetchurl {
    url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-9.0.1.tgz";
    hash = "sha512-hr4ihw+DBqcvrsEDioRO31Z17x71pUYoNe/4h6Z0wB72p7MU7/9gH8Q3s12NFhHPfYBBOV3qyfUxmr/Yn3shnQ==";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
  };
  "debug@4.4.3" = fetchurl {
    url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
    hash = "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
  };
  "decode-named-character-reference@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/decode-named-character-reference/-/decode-named-character-reference-1.3.0.tgz";
    hash = "sha512-GtpQYB283KrPp6nRw50q3U9/VfOutZOe103qlN7BPP6Ad27xYnOIWv4lPzo8HCAL+mMZofJ9KEy30fq6MfaK6Q==";
  };
  "defu@6.1.7" = fetchurl {
    url = "https://registry.npmjs.org/defu/-/defu-6.1.7.tgz";
    hash = "sha512-7z22QmUWiQ/2d0KkdYmANbRUVABpZ9SNYyH5vx6PZ+nE5bcC0l7uFvEfHlyld/HcGBFTL536ClDt3DEcSlEJAQ==";
  };
  "dequal@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz";
    hash = "sha512-0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
  };
  "destr@2.0.5" = fetchurl {
    url = "https://registry.npmjs.org/destr/-/destr-2.0.5.tgz";
    hash = "sha512-ugFTXCtDZunbzasqBxrK93Ik/DRYsO6S/fedkWEMKqt04xZ4csmnmwGDBAb07QWNaGMAmnTIemsYZCksjATwsA==";
  };
  "detect-indent@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/detect-indent/-/detect-indent-6.1.0.tgz";
    hash = "sha512-reYkTUJAZb9gUuZ2RvVCNhVHdg62RHnJ7WJl8ftMi4diZ6NWlciOzQN88pUhSELEwflJht4oQDv0F0BMlwaYtA==";
  };
  "devlop@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/devlop/-/devlop-1.1.0.tgz";
    hash = "sha512-RWmIqhcFf1lRYBvNmr7qTNuyCt/7/ns2jbpp1+PalgE/rDQcBT0fioSMUpJ93irlUhC5hrg4cYqe6U+0ImW0rA==";
  };
  "dir-glob@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/dir-glob/-/dir-glob-3.0.1.tgz";
    hash = "sha512-WkrWp9GR4KXfKGYzOLmTuGVi1UWFfws377n9cc55/tb6DuqyF6pcQ5AbiHEshaDpY9v6oaSr2XCDidGmMwdzIA==";
  };
  "dot-prop@5.3.0" = fetchurl {
    url = "https://registry.npmjs.org/dot-prop/-/dot-prop-5.3.0.tgz";
    hash = "sha512-QM8q3zDe58hqUqjraQOmzZ1LIH9SWQJTlEKCH4kJ2oQvLZk7RbQXvtDM2XEq3fwkV9CCvvH4LA0AV+ogFsBM2Q==";
  };
  "emoji-regex@10.6.0" = fetchurl {
    url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.6.0.tgz";
    hash = "sha512-toUI84YS5YmxW219erniWD0CIVOo46xGKColeNQRgOzDorgBi1v4D71/OFzgD9GO2UGKIv1C3Sp8DAn0+j5w7A==";
  };
  "enquirer@2.4.1" = fetchurl {
    url = "https://registry.npmjs.org/enquirer/-/enquirer-2.4.1.tgz";
    hash = "sha512-rRqJg/6gd538VHvR3PSrdRBb/1Vy2YfzHqzvbhGIQpDRKIa4FgV/54b5Q1xYSxOOwKvjXweS26E0Q+nAMwp2pQ==";
  };
  "entities@4.5.0" = fetchurl {
    url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
    hash = "sha512-V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
  };
  "env-paths@2.2.1" = fetchurl {
    url = "https://registry.npmjs.org/env-paths/-/env-paths-2.2.1.tgz";
    hash = "sha512-+h1lkLKhZMTYjog1VEpJNG7NZJWcuc2DDk/qsqSTRRCOXiLjeQ1d1/udrUGhqMxUgAlwKNZ0cf2uqan5GLuS2A==";
  };
  "error-ex@1.3.4" = fetchurl {
    url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.4.tgz";
    hash = "sha512-sqQamAnR14VgCr1A618A3sGrygcpK+HEbenA/HiEAkkUwcZIIB/tgWqHFxWgOyDh4nB4JCRimh79dR5Ywc9MDQ==";
  };
  "es-toolkit@1.47.0" = fetchurl {
    url = "https://registry.npmjs.org/es-toolkit/-/es-toolkit-1.47.0.tgz";
    hash = "sha512-n1GuoD0WEQZMBk5tttoZSqwgyLx01oqa5XsBmCHwPyNe1S9jPBEmtR2pSgp2kJuWE3ciFZ6yRHmY4pM4C3OOkw==";
  };
  "escalade@3.2.0" = fetchurl {
    url = "https://registry.npmjs.org/escalade/-/escalade-3.2.0.tgz";
    hash = "sha512-WUj2qlxaQtO4g6Pq5c29GTcWGDyd8itL8zTlipgECz3JesAiiOKotd8JU6otB3PACgG6xkJUyVhboMS+bje/jA==";
  };
  "esprima@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
    hash = "sha512-eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
  };
  "exsolve@1.0.8" = fetchurl {
    url = "https://registry.npmjs.org/exsolve/-/exsolve-1.0.8.tgz";
    hash = "sha512-LmDxfWXwcTArk8fUEnOfSZpHOJ6zOMUJKOtFLFqJLoKJetuQG874Uc7/Kki7zFLzYybmZhp1M7+98pfMqeX8yA==";
  };
  "extendable-error@0.1.7" = fetchurl {
    url = "https://registry.npmjs.org/extendable-error/-/extendable-error-0.1.7.tgz";
    hash = "sha512-UOiS2in6/Q0FK0R0q6UY9vYpQ21mr/Qn1KOnte7vsACuNJf514WvCCUHSRCPcgjPT2bAhNIJdlE6bVap1GKmeg==";
  };
  "fast-deep-equal@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
    hash = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
  };
  "fast-glob@3.3.3" = fetchurl {
    url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.3.3.tgz";
    hash = "sha512-7MptL8U0cqcFdzIzwOTHoilX9x5BrNqye7Z/LuC7kCMRio1EMSyqRK3BEAUD7sXRq4iT4AzTVuZdhgQ2TCvYLg==";
  };
  "fast-uri@3.1.2" = fetchurl {
    url = "https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.2.tgz";
    hash = "sha512-rVjf7ArG3LTk+FS6Yw81V1DLuZl1bRbNrev6Tmd/9RaroeeRRJhAt7jg/6YFxbvAQXUCavSoZhPPj6oOx+5KjQ==";
  };
  "fastq@1.20.1" = fetchurl {
    url = "https://registry.npmjs.org/fastq/-/fastq-1.20.1.tgz";
    hash = "sha512-GGToxJ/w1x32s/D2EKND7kTil4n8OVk/9mycTc4VDza13lOvpUZTGX3mFSCtV9ksdGBVzvsyAVLM6mHFThxXxw==";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
  };
  "fill-range@7.1.1" = fetchurl {
    url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
    hash = "sha512-YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
  };
  "find-up@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz";
    hash = "sha512-PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==";
  };
  "fs-extra@7.0.1" = fetchurl {
    url = "https://registry.npmjs.org/fs-extra/-/fs-extra-7.0.1.tgz";
    hash = "sha512-YJDaCJZEnBmcbw13fvdAM9AwNOJwOzrE4pqMqBq5nFiEqXUqHwlK4B+3pUw6JNvfSPtX05xFHtYy/1ni01eGCw==";
  };
  "fs-extra@8.1.0" = fetchurl {
    url = "https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz";
    hash = "sha512-yhlQgA6mnOJUKOsRUFsgJdQCvkKhcz8tlZG5HBQfReYZy46OwLcY+Zia0mtdHsOo9y/hP+CxMN0TU9QxoOtG4g==";
  };
  "get-caller-file@2.0.5" = fetchurl {
    url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
    hash = "sha512-DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
  };
  "get-east-asian-width@1.6.0" = fetchurl {
    url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.6.0.tgz";
    hash = "sha512-QRbvDIbx6YklUe6RxeTeleMR0yv3cYH6PsPZHcnVn7xv7zO1BHN8r0XETu8n6Ye3Q+ahtSarc3WgtNWmehIBfA==";
  };
  "giget@3.3.0" = fetchurl {
    url = "https://registry.npmjs.org/giget/-/giget-3.3.0.tgz";
    hash = "sha512-gzi2D96p+AMfDcmJHGDj3KJ9NRiwvlFAU5yfa3ROwWZmFUjX4P43x3BcyRaOMMLto1vUo7C+86+MFhYTl6Ryiw==";
  };
  "git-raw-commits@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/git-raw-commits/-/git-raw-commits-5.0.1.tgz";
    hash = "sha512-Y+csSm2GD/PCSh6Isd/WiMjNAydu0VBiG9J7EdQsNA5P9uXvLayqjmTsNlK5Gs9IhblFZqOU0yid5Il5JPoLiQ==";
  };
  "glob-parent@5.1.2" = fetchurl {
    url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
    hash = "sha512-AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
  };
  "global-directory@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/global-directory/-/global-directory-5.0.0.tgz";
    hash = "sha512-1pgFdhK3J2LeM+dVf2Pd424yHx2ou338lC0ErNP2hPx4j8eW1Sp0XqSjNxtk6Tc4Kr5wlWtSvz8cn2yb7/SG/w==";
  };
  "globby@11.1.0" = fetchurl {
    url = "https://registry.npmjs.org/globby/-/globby-11.1.0.tgz";
    hash = "sha512-jhIXaOzy1sb8IyocaruWSn1TjmnBVs8Ayhcy83rmxNJ8q2uWKCAj3CnJY+KpGSXCueAPc0i05kVvVKtP1t9S3g==";
  };
  "globby@16.2.0" = fetchurl {
    url = "https://registry.npmjs.org/globby/-/globby-16.2.0.tgz";
    hash = "sha512-QrJia2qDf5BB/V6HYlDTs0I0lBahyjLzpGQg3KT7FnCdTonAyPy2RtY802m2k4ALx6Dp752f82WsOczEVr3l6Q==";
  };
  "graceful-fs@4.2.11" = fetchurl {
    url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
    hash = "sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
  };
  "human-id@4.2.0" = fetchurl {
    url = "https://registry.npmjs.org/human-id/-/human-id-4.2.0.tgz";
    hash = "sha512-K3GbkIWqyvvlpfhBPlbEvD97TtqBpAYA4kt+cn2lD2x2HuohzZCibcA2nOlnJT6exqvJLggoB5nv2dNf192nEA==";
  };
  "iconv-lite@0.7.2" = fetchurl {
    url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.7.2.tgz";
    hash = "sha512-im9DjEDQ55s9fL4EYzOAv0yMqmMBSZp6G0VvFyTMPKWxiSBHUj9NW/qqLmXUwXrrM7AvqSlTCfvqRb0cM8yYqw==";
  };
  "ignore@5.3.2" = fetchurl {
    url = "https://registry.npmjs.org/ignore/-/ignore-5.3.2.tgz";
    hash = "sha512-hsBTNUqQTDwkWtcdYI2i06Y/nUBEsNEDJKjWdigLvegy8kDuJAS8uRlpkkcQpyEXL0Z/pjDy5HBmMjRCJ2gq+g==";
  };
  "ignore@7.0.5" = fetchurl {
    url = "https://registry.npmjs.org/ignore/-/ignore-7.0.5.tgz";
    hash = "sha512-Hs59xBNfUIunMFgWAbGX5cq6893IbWg4KnrjbYwX3tx0ztorVgTDA6B2sxf8ejHJ4wz8BqGUMYlnzNBer5NvGg==";
  };
  "import-fresh@3.3.1" = fetchurl {
    url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.1.tgz";
    hash = "sha512-TR3KfrTZTYLPB6jUjfx6MF9WcWrHL9su5TObK4ZkYgBdWKPOFoSoQIdEuTuR82pmtxH2spWG9h6etwfr1pLBqQ==";
  };
  "ini@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/ini/-/ini-6.0.0.tgz";
    hash = "sha512-IBTdIkzZNOpqm7q3dRqJvMaldXjDHWkEDfrwGEQTs5eaQMWV+djAhR+wahyNNMAa+qpbDUhBMVt4ZKNwpPm7xQ==";
  };
  "is-alphabetical@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-alphabetical/-/is-alphabetical-2.0.1.tgz";
    hash = "sha512-FWyyY60MeTNyeSRpkM2Iry0G9hpr7/9kD40mD/cGQEuilcZYS4okz8SN2Q6rLCJ8gbCt6fN+rC+6tMGS99LaxQ==";
  };
  "is-alphanumerical@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-alphanumerical/-/is-alphanumerical-2.0.1.tgz";
    hash = "sha512-hmbYhX/9MUMF5uh7tOXyK/n0ZvWpad5caBA17GsC6vyuCqaWliRG5K1qS9inmUhEMaOBIW7/whAnSwveW/LtZw==";
  };
  "is-arrayish@0.2.1" = fetchurl {
    url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
    hash = "sha512-zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg==";
  };
  "is-decimal@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-decimal/-/is-decimal-2.0.1.tgz";
    hash = "sha512-AAB9hiomQs5DXWcRB1rqsxGUstbRroFOPPVAomNk/3XHR5JyEZChOyTWe2oayKnsSsr/kcGqF+z6yuH6HHpN0A==";
  };
  "is-extglob@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
    hash = "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
  };
  "is-glob@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
    hash = "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
  };
  "is-hexadecimal@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-hexadecimal/-/is-hexadecimal-2.0.1.tgz";
    hash = "sha512-DgZQp241c8oO6cA1SbTEWiXeoxV42vlcJxgH+B3hi1AiqqKruZR3ZGF8In3fj4+/y/7rHvlOZLZtgJ/4ttYGZg==";
  };
  "is-number@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
    hash = "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
  };
  "is-obj@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
    hash = "sha512-drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
  };
  "is-path-inside@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-4.0.0.tgz";
    hash = "sha512-lJJV/5dYS+RcL8uQdBDW9c9uWFLLBNRyFhnAKXw5tVqLlKZ4RMGZKv+YQ/IA3OhD+RpbJa1LLFM1FQPGyIXvOA==";
  };
  "is-plain-obj@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-4.1.0.tgz";
    hash = "sha512-+Pgi+vMuUNkJyExiMBt5IlFoMyKnr5zhJ4Uspz58WOhBF5QoIZkFyNHIbBAtHwzVAgk5RtndVNsDRN61/mmDqg==";
  };
  "is-subdir@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/is-subdir/-/is-subdir-1.2.0.tgz";
    hash = "sha512-2AT6j+gXe/1ueqbW6fLZJiIw3F8iXGJtt0yDrZaBhAZEG1raiTxKWU+IPqMCzQAXOUCKdA4UDMgacKH25XG2Cw==";
  };
  "is-windows@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
    hash = "sha512-eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "jiti@2.6.1" = fetchurl {
    url = "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz";
    hash = "sha512-ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
  };
  "jju@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/jju/-/jju-1.4.0.tgz";
    hash = "sha512-8wb9Yw966OSxApiCt0K3yNJL8pnNeIv+OEq2YMidz4FKP6nonSRoOXc80iXY4JaN2FC11B9qsNmDsm+ZOfMROA==";
  };
  "js-tokens@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
    hash = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
  };
  "js-yaml@3.14.2" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.2.tgz";
    hash = "sha512-PMSmkqxr106Xa156c2M265Z+FTrPl+oxd/rgOQy2tijQeK5TxQ43psO1ZCwhVOSdnn+RzkzlRz/eY4BgJBYVpg==";
  };
  "js-yaml@4.1.1" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.1.tgz";
    hash = "sha512-qQKT4zQxXl8lLwBtHMWwaTcGfFOZviOJet3Oy/xmGk2gZH677CJM9EvtfdSkgWcATZhj/55JZ0rmy3myCT5lsA==";
  };
  "js-yaml@5.2.0" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-5.2.0.tgz";
    hash = "sha512-YeLUMlvR4Ou1B119LIaM0r65JvbOBooJDc9yEu0dClb/uSC5P4FrLU8OCCz/HXWvtPoIrR0dRzABTjo1sTN9Bw==";
  };
  "json-parse-even-better-errors@2.3.1" = fetchurl {
    url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz";
    hash = "sha512-xyFwyhro/JEof6Ghe2iz2NcXoj2sloNsWr/XsERDK/oiPCfaNhl5ONfp+jQdAZRQQ0IJWNzH9zIZF7li91kh2w==";
  };
  "json-schema-traverse@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
    hash = "sha512-NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
  };
  "jsonc-parser@3.3.1" = fetchurl {
    url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz";
    hash = "sha512-HUgH65KyejrUFPvHFPbqOY0rsFip3Bo5wb4ngvdi1EpCYWUQDC5V+Y7mZws+DLkr4M//zQJoanu1SP+87Dv1oQ==";
  };
  "jsonfile@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
    hash = "sha512-m6F1R3z8jjlf2imQHS2Qez5sjKWQzbuuhuJ/FKYFRZvPE3PuHcSMVZzfsLhGVOkfd20obL5SWEBew5ShlquNxg==";
  };
  "jsonpointer@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-5.0.1.tgz";
    hash = "sha512-p/nXbhSEcu3pZRdkW1OfJhpsVtW1gd4Wa1fnQc9YLiTfAjn0312eMKimbdIQzuZl9aa9xUGaRlP9T/CJE/ditQ==";
  };
  "jsr@0.14.3" = fetchurl {
    url = "https://registry.npmjs.org/jsr/-/jsr-0.14.3.tgz";
    hash = "sha512-PGxnDepx7vwJoZQe2SHbyBiFfpGwsOKmX4kn/wZZqfMafV7fjXqTxSaX6lp9QHYkSTLKkER+P/wmrZY3gVJNzg==";
  };
  "katex@0.16.47" = fetchurl {
    url = "https://registry.npmjs.org/katex/-/katex-0.16.47.tgz";
    hash = "sha512-Eeo8Ys1doU1z+x8AZsPpQu+p/QcZBI5PeOo7QGQdy2x2m0MU/hYagBbGOmXwr5KVbEfVuWv9LpnQWeehogurjg==";
  };
  "lines-and-columns@1.2.4" = fetchurl {
    url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.2.4.tgz";
    hash = "sha512-7ylylesZQ/PV29jhEDl3Ufjo6ZX7gCqJr5F7PKrqc93v7fzSymt1BpwEU8nAUXs8qzzvqhbjhK5QZg6Mt/HkBg==";
  };
  "linkify-it@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/linkify-it/-/linkify-it-5.0.1.tgz";
    hash = "sha512-wVoTjP4Q6R0NW5hiZkVJaFZPWgtXfoGF+6LucL3/FtiNjmcHhYjEr5f1Kqjirc1nBW07J/ZuRFumqr2oqccEWg==";
  };
  "locate-path@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz";
    hash = "sha512-t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==";
  };
  "lodash.startcase@4.4.0" = fetchurl {
    url = "https://registry.npmjs.org/lodash.startcase/-/lodash.startcase-4.4.0.tgz";
    hash = "sha512-+WKqsK294HMSc2jEbNgpHpd0JfIBhp7rEV4aqXWqFr6AlXov+SlcgB1Fv01y2kGe3Gc8nMW7VA0SrGuSkRfIEg==";
  };
  "markdown-it@14.2.0" = fetchurl {
    url = "https://registry.npmjs.org/markdown-it/-/markdown-it-14.2.0.tgz";
    hash = "sha512-1TGiQiJVRQ3NPmZH6sx5Cfnmg6GQm9jvC1ch4TK511NjSJvjzKLzn5pPfZRNZkRPZP0HqCioSndqH8v2nRaWVQ==";
  };
  "markdownlint-cli2-formatter-default@0.0.6" = fetchurl {
    url = "https://registry.npmjs.org/markdownlint-cli2-formatter-default/-/markdownlint-cli2-formatter-default-0.0.6.tgz";
    hash = "sha512-VVDGKsq9sgzu378swJ0fcHfSicUnMxnL8gnLm/Q4J/xsNJ4e5bA6lvAz7PCzIl0/No0lHyaWdqVD2jotxOSFMQ==";
  };
  "markdownlint-cli2@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/markdownlint-cli2/-/markdownlint-cli2-0.23.0.tgz";
    hash = "sha512-1nmgQmU/ZTMRVwYCDs7i1HI3zfBISnT2NNRv+9V01oOLZbAtqL+a7tldpPhBWBVBten3FqhMCGV6EUh9McqutQ==";
  };
  "markdownlint@0.41.0" = fetchurl {
    url = "https://registry.npmjs.org/markdownlint/-/markdownlint-0.41.0.tgz";
    hash = "sha512-xMUI3ChBuRuxuLF4ENvCZyS8z/+Jly1coUcZwErKLIB3sDj7ojpaTBa1e9YVPhSN4jGEIjYGQCldbTJS/hqS+A==";
  };
  "mdurl@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/mdurl/-/mdurl-2.0.0.tgz";
    hash = "sha512-Lf+9+2r+Tdp5wXDXC4PcIBjTDtq4UKjCPMQhKIuzpJNW0b96kVqSwW0bT7FhRSfmAiFYgP+SCRvdrDozfh0U5w==";
  };
  "meow@13.2.0" = fetchurl {
    url = "https://registry.npmjs.org/meow/-/meow-13.2.0.tgz";
    hash = "sha512-pxQJQzB6djGPXh08dacEloMFopsOqGVRKFPYvPOt9XDZ1HasbgDZA74CJGreSU4G3Ak7EFJGoiH2auq+yXISgA==";
  };
  "merge2@1.4.1" = fetchurl {
    url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
    hash = "sha512-8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
  };
  "micromark-core-commonmark@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/micromark-core-commonmark/-/micromark-core-commonmark-2.0.3.tgz";
    hash = "sha512-RDBrHEMSxVFLg6xvnXmb1Ayr2WzLAWjeSATAoxwKYJV94TeNavgoIdA0a9ytzDSVzBy2YKFK+emCPOEibLeCrg==";
  };
  "micromark-extension-directive@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/micromark-extension-directive/-/micromark-extension-directive-4.0.0.tgz";
    hash = "sha512-/C2nqVmXXmiseSSuCdItCMho7ybwwop6RrrRPk0KbOHW21JKoCldC+8rFOaundDoRBUWBnJJcxeA/Kvi34WQXg==";
  };
  "micromark-extension-gfm-autolink-literal@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/micromark-extension-gfm-autolink-literal/-/micromark-extension-gfm-autolink-literal-2.1.0.tgz";
    hash = "sha512-oOg7knzhicgQ3t4QCjCWgTmfNhvQbDDnJeVu9v81r7NltNCVmhPy1fJRX27pISafdjL+SVc4d3l48Gb6pbRypw==";
  };
  "micromark-extension-gfm-footnote@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/micromark-extension-gfm-footnote/-/micromark-extension-gfm-footnote-2.1.0.tgz";
    hash = "sha512-/yPhxI1ntnDNsiHtzLKYnE3vf9JZ6cAisqVDauhp4CEHxlb4uoOTxOCJ+9s51bIB8U1N1FJ1RXOKTIlD5B/gqw==";
  };
  "micromark-extension-gfm-table@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-extension-gfm-table/-/micromark-extension-gfm-table-2.1.1.tgz";
    hash = "sha512-t2OU/dXXioARrC6yWfJ4hqB7rct14e8f7m0cbI5hUmDyyIlwv5vEtooptH8INkbLzOatzKuVbQmAYcbWoyz6Dg==";
  };
  "micromark-extension-math@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/micromark-extension-math/-/micromark-extension-math-3.1.0.tgz";
    hash = "sha512-lvEqd+fHjATVs+2v/8kg9i5Q0AP2k85H0WUOwpIVvUML8BapsMvh1XAogmQjOCsLpoKRCVQqEkQBB3NhVBcsOg==";
  };
  "micromark-factory-destination@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-factory-destination/-/micromark-factory-destination-2.0.1.tgz";
    hash = "sha512-Xe6rDdJlkmbFRExpTOmRj9N3MaWmbAgdpSrBQvCFqhezUn4AHqJHbaEnfbVYYiexVSs//tqOdY/DxhjdCiJnIA==";
  };
  "micromark-factory-label@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-factory-label/-/micromark-factory-label-2.0.1.tgz";
    hash = "sha512-VFMekyQExqIW7xIChcXn4ok29YE3rnuyveW3wZQWWqF4Nv9Wk5rgJ99KzPvHjkmPXF93FXIbBp6YdW3t71/7Vg==";
  };
  "micromark-factory-space@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-factory-space/-/micromark-factory-space-2.0.1.tgz";
    hash = "sha512-zRkxjtBxxLd2Sc0d+fbnEunsTj46SWXgXciZmHq0kDYGnck/ZSGj9/wULTV95uoeYiK5hRXP2mJ98Uo4cq/LQg==";
  };
  "micromark-factory-title@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-factory-title/-/micromark-factory-title-2.0.1.tgz";
    hash = "sha512-5bZ+3CjhAd9eChYTHsjy6TGxpOFSKgKKJPJxr293jTbfry2KDoWkhBb6TcPVB4NmzaPhMs1Frm9AZH7OD4Cjzw==";
  };
  "micromark-factory-whitespace@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-factory-whitespace/-/micromark-factory-whitespace-2.0.1.tgz";
    hash = "sha512-Ob0nuZ3PKt/n0hORHyvoD9uZhr+Za8sFoP+OnMcnWK5lngSzALgQYKMr9RJVOWLqQYuyn6ulqGWSXdwf6F80lQ==";
  };
  "micromark-util-character@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-character/-/micromark-util-character-2.1.1.tgz";
    hash = "sha512-wv8tdUTJ3thSFFFJKtpYKOYiGP2+v96Hvk4Tu8KpCAsTMs6yi+nVmGh1syvSCsaxz45J6Jbw+9DD6g97+NV67Q==";
  };
  "micromark-util-chunked@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-chunked/-/micromark-util-chunked-2.0.1.tgz";
    hash = "sha512-QUNFEOPELfmvv+4xiNg2sRYeS/P84pTW0TCgP5zc9FpXetHY0ab7SxKyAQCNCc1eK0459uoLI1y5oO5Vc1dbhA==";
  };
  "micromark-util-classify-character@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-classify-character/-/micromark-util-classify-character-2.0.1.tgz";
    hash = "sha512-K0kHzM6afW/MbeWYWLjoHQv1sgg2Q9EccHEDzSkxiP/EaagNzCm7T/WMKZ3rjMbvIpvBiZgwR3dKMygtA4mG1Q==";
  };
  "micromark-util-combine-extensions@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-combine-extensions/-/micromark-util-combine-extensions-2.0.1.tgz";
    hash = "sha512-OnAnH8Ujmy59JcyZw8JSbK9cGpdVY44NKgSM7E9Eh7DiLS2E9RNQf0dONaGDzEG9yjEl5hcqeIsj4hfRkLH/Bg==";
  };
  "micromark-util-decode-numeric-character-reference@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-decode-numeric-character-reference/-/micromark-util-decode-numeric-character-reference-2.0.2.tgz";
    hash = "sha512-ccUbYk6CwVdkmCQMyr64dXz42EfHGkPQlBj5p7YVGzq8I7CtjXZJrubAYezf7Rp+bjPseiROqe7G6foFd+lEuw==";
  };
  "micromark-util-encode@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-encode/-/micromark-util-encode-2.0.1.tgz";
    hash = "sha512-c3cVx2y4KqUnwopcO9b/SCdo2O67LwJJ/UyqGfbigahfegL9myoEFoDYZgkT7f36T0bLrM9hZTAaAyH+PCAXjw==";
  };
  "micromark-util-html-tag-name@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-html-tag-name/-/micromark-util-html-tag-name-2.0.1.tgz";
    hash = "sha512-2cNEiYDhCWKI+Gs9T0Tiysk136SnR13hhO8yW6BGNyhOC4qYFnwF1nKfD3HFAIXA5c45RrIG1ub11GiXeYd1xA==";
  };
  "micromark-util-normalize-identifier@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-normalize-identifier/-/micromark-util-normalize-identifier-2.0.1.tgz";
    hash = "sha512-sxPqmo70LyARJs0w2UclACPUUEqltCkJ6PhKdMIDuJ3gSf/Q+/GIe3WKl0Ijb/GyH9lOpUkRAO2wp0GVkLvS9Q==";
  };
  "micromark-util-resolve-all@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-resolve-all/-/micromark-util-resolve-all-2.0.1.tgz";
    hash = "sha512-VdQyxFWFT2/FGJgwQnJYbe1jjQoNTS4RjglmSjTUlpUMa95Htx9NHeYW4rGDJzbjvCsl9eLjMQwGeElsqmzcHg==";
  };
  "micromark-util-sanitize-uri@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-sanitize-uri/-/micromark-util-sanitize-uri-2.0.1.tgz";
    hash = "sha512-9N9IomZ/YuGGZZmQec1MbgxtlgougxTodVwDzzEouPKo3qFWvymFHWcnDi2vzV1ff6kas9ucW+o3yzJK9YB1AQ==";
  };
  "micromark-util-subtokenize@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-subtokenize/-/micromark-util-subtokenize-2.1.0.tgz";
    hash = "sha512-XQLu552iSctvnEcgXw6+Sx75GflAPNED1qx7eBJ+wydBb2KCbRZe+NwvIEEMM83uml1+2WSXpBAcp9IUCgCYWA==";
  };
  "micromark-util-symbol@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-symbol/-/micromark-util-symbol-2.0.1.tgz";
    hash = "sha512-vs5t8Apaud9N28kgCrRUdEed4UJ+wWNvicHLPxCa9ENlYuAY31M0ETy5y1vA33YoNPDFTghEbnh6efaE8h4x0Q==";
  };
  "micromark-util-types@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/micromark-util-types/-/micromark-util-types-2.0.2.tgz";
    hash = "sha512-Yw0ECSpJoViF1qTU4DC6NwtC4aWGt1EkzaQB8KPPyCRR8z9TWeV0HbEFGTO+ZY1wB22zmxnJqhPyTpOVCpeHTA==";
  };
  "micromark@4.0.2" = fetchurl {
    url = "https://registry.npmjs.org/micromark/-/micromark-4.0.2.tgz";
    hash = "sha512-zpe98Q6kvavpCr1NPVSCMebCKfD7CA2NqZ+rykeNhONIJBpc1tFKt9hucLGwha3jNTNI8lHpctWJWoimVF4PfA==";
  };
  "micromatch@4.0.8" = fetchurl {
    url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
    hash = "sha512-PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
  };
  "minimatch@10.2.5" = fetchurl {
    url = "https://registry.npmjs.org/minimatch/-/minimatch-10.2.5.tgz";
    hash = "sha512-MULkVLfKGYDFYejP07QOurDLLQpcjk7Fw+7jXS2R2czRQzR56yHRveU5NDJEOviH+hETZKSkIk5c+T23GjFUMg==";
  };
  "minipass@7.1.3" = fetchurl {
    url = "https://registry.npmjs.org/minipass/-/minipass-7.1.3.tgz";
    hash = "sha512-tEBHqDnIoM/1rXME1zgka9g6Q2lcoCkxHLuc7ODJ5BxbP5d4c2Z5cGgtXAku59200Cx7diuHTOYfSBD8n6mm8A==";
  };
  "minizlib@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/minizlib/-/minizlib-3.1.0.tgz";
    hash = "sha512-KZxYo1BUkWD2TVFLr0MQoM8vUUigWD3LlD83a/75BqC+4qE0Hb1Vo5v1FgcfaNXvfXzr+5EhQ6ing/CaBijTlw==";
  };
  "mri@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
    hash = "sha512-tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
  };
  "ms@2.1.3" = fetchurl {
    url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
    hash = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
  };
  "node-stream-zip@1.15.0" = fetchurl {
    url = "https://registry.npmjs.org/node-stream-zip/-/node-stream-zip-1.15.0.tgz";
    hash = "sha512-LN4fydt9TqhZhThkZIVQnF9cwjU3qmUH9h78Mx/K7d3VvfRqqwthLwJEUOEL0QPZ0XQmNN7be5Ggit5+4dq3Bw==";
  };
  "opencode-ai@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-ai/-/opencode-ai-1.17.4.tgz";
    hash = "sha512-PKjjpN6nl7AMpMgq9mJvK9C190aLnxmq0bOi0/sz9cOvEzRpFQFfdL7NmYfoQbXwNtaSYC49eDGGU0hFTtwQkg==";
  };
  "opencode-darwin-arm64@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-darwin-arm64/-/opencode-darwin-arm64-1.17.4.tgz";
    hash = "sha512-2FZNZ8FRSY6jw4dbTHqyrSZei/hgFcSI1VMBAyiE5GXMrHtyGrw36CXdzC5/4x9GKZvv5AwSO5bGffNvoW8qYw==";
  };
  "opencode-darwin-x64-baseline@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-darwin-x64-baseline/-/opencode-darwin-x64-baseline-1.17.4.tgz";
    hash = "sha512-mODxs/hyOxq0bAhabo1W5nRpyYjkhKKtlIdoo4UXVzOMGQmAmEA7TkP6XhAdPq6LH6XjdlZFHsOWO4NC5o/yCw==";
  };
  "opencode-darwin-x64@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-darwin-x64/-/opencode-darwin-x64-1.17.4.tgz";
    hash = "sha512-wtyZzCwO1WsVgpRNBmrn0NysL7uDBY3K9OoDV3kJrxEAMoJPREc14yscs5Mp1wspmx0vO5WMECe0eVToaYtSFw==";
  };
  "opencode-linux-arm64-musl@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-linux-arm64-musl/-/opencode-linux-arm64-musl-1.17.4.tgz";
    hash = "sha512-8axm1+sBqKJyFMQI8kquvskXEhh0xzXyNq22h/w0zBirN+cUQ7rPKARJ6gczVe60C6gHfS+bN0IOEszv2bUcSA==";
  };
  "opencode-linux-arm64@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-linux-arm64/-/opencode-linux-arm64-1.17.4.tgz";
    hash = "sha512-6Gp1BBwKgMgyGGFMqMFdR1TI6KZO9WiAaAZ7DDtcRMRnrvd0CXO+gGAFJKqQZ7RDnbPHhpaXlt0ydGdoF0FN+g==";
  };
  "opencode-linux-x64-baseline-musl@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-linux-x64-baseline-musl/-/opencode-linux-x64-baseline-musl-1.17.4.tgz";
    hash = "sha512-/KH1OVX7Rp94VKHqujFXhGxpAF/GNDU8BZRmBvdYkK38ibmcFGrB7FSGhBey1rE8W0e2Lh04Fp563W5LtnarQA==";
  };
  "opencode-linux-x64-baseline@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-linux-x64-baseline/-/opencode-linux-x64-baseline-1.17.4.tgz";
    hash = "sha512-+qBaxCJvb5exr39xc0TXSe5oV1Fj9KsHsbBgEfa1VuqyWkmAw82LAYcIOohNGHBYSv/dyOY4fNiSTgLWpzNZdw==";
  };
  "opencode-linux-x64-musl@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-linux-x64-musl/-/opencode-linux-x64-musl-1.17.4.tgz";
    hash = "sha512-dPVhJ2A21ePNVq15YOKX77N40SenJD6kdzyvtmVLJmbNzp2kvSqZ4Fqsdc4EZTWu62Yuuv//QisUsxUct2Bn9g==";
  };
  "opencode-linux-x64@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-linux-x64/-/opencode-linux-x64-1.17.4.tgz";
    hash = "sha512-KEjLRLdobfwThV0ik1pO/D9sy+uykhA+Sp2yy52WyNYAYqTEuKxz3265EeY6tIzTZG7HI/wENiDTCvZsVrpsfg==";
  };
  "opencode-windows-arm64@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-windows-arm64/-/opencode-windows-arm64-1.17.4.tgz";
    hash = "sha512-5DTJIzD8w1bI3sf2dLmHa6Jseq6+pdcRLkldJYsm3gCl9i5XZ2gV+tXiUOpsml3XhJPL96oWvlC1jrW89DeRoQ==";
  };
  "opencode-windows-x64-baseline@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-windows-x64-baseline/-/opencode-windows-x64-baseline-1.17.4.tgz";
    hash = "sha512-J8EX2wOPkZSJeLzVsGuGSo+5cuWJQzCytR4H3UVuqZ8lT1IY0oViE7dPc/MKWt2ueZKIGWoPWZnlG6ByplRgvg==";
  };
  "opencode-windows-x64@1.17.4" = fetchurl {
    url = "https://registry.npmjs.org/opencode-windows-x64/-/opencode-windows-x64-1.17.4.tgz";
    hash = "sha512-rYLkfkhRdT5r+C5Xkx1xMd4jgESCSq5pA50WrNbMqJA+Fl36Kf3fRlhBXX70ODamcyJjGBsy03RFCN/poVeoxA==";
  };
  "outdent@0.5.0" = fetchurl {
    url = "https://registry.npmjs.org/outdent/-/outdent-0.5.0.tgz";
    hash = "sha512-/jHxFIzoMXdqPzTaCpFzAAWhpkSjZPF4Vsn6jAfNpmbH/ymsmd7Qc6VE9BGn0L6YMj6uwpQLxCECpus4ukKS9Q==";
  };
  "oxfmt@0.54.0" = fetchurl {
    url = "https://registry.npmjs.org/oxfmt/-/oxfmt-0.54.0.tgz";
    hash = "sha512-DjnMwn7smSLF+Mc2+pRItnuPftm/dkUFpY/d4+33y9TfKrsHZo8GLhmUg9BrOIUEy94Rlom1Q11N6vuhE+e0oQ==";
  };
  "oxlint-tsgolint@0.23.0" = fetchurl {
    url = "https://registry.npmjs.org/oxlint-tsgolint/-/oxlint-tsgolint-0.23.0.tgz";
    hash = "sha512-3mBv3CoPbh8dFbzfDGIWa2ytZjn2v+3EX4aKRXjIhsoGFzG8GCjfRirz3rwZf1wYbZzsNLTSgpw8VjQuWdp/jA==";
  };
  "oxlint@1.69.0" = fetchurl {
    url = "https://registry.npmjs.org/oxlint/-/oxlint-1.69.0.tgz";
    hash = "sha512-ypZkK/aDc5NQV8zIR6s2H2Tl3aNW8FmJ1m9+2qsaYuRenl8vgnHNCGwTHviWJdUQzglOlHFchgopdtGhSy17Rw==";
  };
  "p-filter@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/p-filter/-/p-filter-2.1.0.tgz";
    hash = "sha512-ZBxxZ5sL2HghephhpGAQdoskxplTwr7ICaehZwLIlfL6acuVgZPm8yBNuRAFBGEqtD/hmUeq9eqLg2ys9Xr/yw==";
  };
  "p-limit@2.3.0" = fetchurl {
    url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
    hash = "sha512-//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
  };
  "p-limit@7.3.0" = fetchurl {
    url = "https://registry.npmjs.org/p-limit/-/p-limit-7.3.0.tgz";
    hash = "sha512-7cIXg/Z0M5WZRblrsOla88S4wAK+zOQQWeBYfV3qJuJXMr+LnbYjaadrFaS0JILfEDPVqHyKnZ1Z/1d6J9VVUw==";
  };
  "p-locate@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz";
    hash = "sha512-R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==";
  };
  "p-map@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/p-map/-/p-map-2.1.0.tgz";
    hash = "sha512-y3b8Kpd8OAN444hxfBbFfj1FY/RjtTd8tzYwhUqNYXx0fXx2iX4maP4Qr6qhIKbQXI02wTLAda4fYUbDagTUFw==";
  };
  "p-try@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
    hash = "sha512-R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
  };
  "package-manager-detector@0.2.11" = fetchurl {
    url = "https://registry.npmjs.org/package-manager-detector/-/package-manager-detector-0.2.11.tgz";
    hash = "sha512-BEnLolu+yuz22S56CU1SUKq3XC3PkwD5wv4ikR4MfGvnRVcmzXR9DwSlW2fEamyTPyXHomBJRzgapeuBvRNzJQ==";
  };
  "parent-module@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
    hash = "sha512-GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
  };
  "parse-entities@4.0.2" = fetchurl {
    url = "https://registry.npmjs.org/parse-entities/-/parse-entities-4.0.2.tgz";
    hash = "sha512-GG2AQYWoLgL877gQIKeRPGO1xF9+eG1ujIb5soS5gPvLQ1y2o8FL90w2QWNdf9I361Mpp7726c+lj3U0qK1uGw==";
  };
  "parse-json@5.2.0" = fetchurl {
    url = "https://registry.npmjs.org/parse-json/-/parse-json-5.2.0.tgz";
    hash = "sha512-ayCKvm/phCGxOkYRSCM82iDwct8/EonSEgCSxWxD7ve6jHggsFl4fZVQBPRNgQoKiuV/odhFrGzQXZwbifC8Rg==";
  };
  "path-exists@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
    hash = "sha512-ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
  };
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
  };
  "path-type@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
    hash = "sha512-gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
  };
  "pend@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
    hash = "sha512-F3asv42UuXchdzt+xXqfW1OGlVBe+mxa2mqI0pg5yAHZPvFmY3Y6drSf/GQ1A86WgWEN9Kzh/WrgKa6iGcHXLg==";
  };
  "picocolors@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
    hash = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
  };
  "picomatch@2.3.2" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.2.tgz";
    hash = "sha512-V7+vQEJ06Z+c5tSye8S+nHUfI51xoXIXjHQ99cQtKUkQqqO1kO/KCJUfZXuB47h/YBlDhah2H3hdUGXn8ie0oA==";
  };
  "picomatch@4.0.4" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.4.tgz";
    hash = "sha512-QP88BAKvMam/3NxH6vj2o21R6MjxZUAd6nlwAS/pnGvN9IVLocLHxGYIzFhg6fUQ+5th6P4dv4eW9jX3DSIj7A==";
  };
  "pify@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
    hash = "sha512-uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
  };
  "pkg-types@2.3.1" = fetchurl {
    url = "https://registry.npmjs.org/pkg-types/-/pkg-types-2.3.1.tgz";
    hash = "sha512-y+ichcgc2LrADuhLNAx8DFjVfgz91pRxfZdI3UDhxHvcVEZsenLO+7XaU5vOp0u/7V/wZ+plyuQxtrDlZJ+yeg==";
  };
  "prettier@2.8.8" = fetchurl {
    url = "https://registry.npmjs.org/prettier/-/prettier-2.8.8.tgz";
    hash = "sha512-tdN8qQGvNjw4CHbY+XXk0JgCXn9QiF21a55rBe5LJAU+kDyC4WQn4+awm2Xfk2lQMk5fKup9XgzTZtGkjBdP9Q==";
  };
  "punycode.js@2.3.1" = fetchurl {
    url = "https://registry.npmjs.org/punycode.js/-/punycode.js-2.3.1.tgz";
    hash = "sha512-uxFIHU0YlHYhDQtV4R9J6a52SLx28BCjT+4ieh7IGbgwVJWO+km431c4yRlREUAsAmt/uMjQUyQHNEPf0M39CA==";
  };
  "quansync@0.2.11" = fetchurl {
    url = "https://registry.npmjs.org/quansync/-/quansync-0.2.11.tgz";
    hash = "sha512-AifT7QEbW9Nri4tAwR5M/uzpBuqfZf+zwaEM/QkzEjj7NBuFD2rBuy0K3dE+8wltbezDV7JMA0WfnCPYRSYbXA==";
  };
  "queue-microtask@1.2.3" = fetchurl {
    url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
    hash = "sha512-NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
  };
  "rc9@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/rc9/-/rc9-3.0.1.tgz";
    hash = "sha512-gMDyleLWVE+i6Sgtc0QbbY6pEKqYs97NGi6isHQPqYlLemPoO8dxQ3uGi0f4NiP98c+jMW6cG1Kx9dDwfvqARQ==";
  };
  "read-yaml-file@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/read-yaml-file/-/read-yaml-file-1.1.0.tgz";
    hash = "sha512-VIMnQi/Z4HT2Fxuwg5KrY174U1VdUIASQVWXXyqtNRtxSr9IYkn1rsI6Tb6HsrHCmB7gVpNwX6JxPTHcH6IoTA==";
  };
  "readdirp@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/readdirp/-/readdirp-5.0.0.tgz";
    hash = "sha512-9u/XQ1pvrQtYyMpZe7DXKv2p5CNvyVwzUB6uhLAnQwHMSgKMBR62lc7AHljaeteeHXn11XTAaLLUVZYVZyuRBQ==";
  };
  "require-from-string@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
    hash = "sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
  };
  "resolve-from@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
    hash = "sha512-pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
  };
  "resolve-from@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
    hash = "sha512-qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
  };
  "reusify@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/reusify/-/reusify-1.1.0.tgz";
    hash = "sha512-g6QUff04oZpHs0eG5p83rFLhHeV00ug/Yf9nZM6fLeUrPguBTkTQOdpAWWspMh55TZfVQDPaN3NQJfbVRAxdIw==";
  };
  "run-parallel@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
    hash = "sha512-5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
  };
  "safer-buffer@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
    hash = "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
  };
  "semiver@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/semiver/-/semiver-1.1.0.tgz";
    hash = "sha512-QNI2ChmuioGC1/xjyYwyZYADILWyW6AmS1UH6gDj/SFUUUS4MBAWs/7mxnkRPc/F4iHezDP+O8t0dO8WHiEOdg==";
  };
  "semver@7.8.1" = fetchurl {
    url = "https://registry.npmjs.org/semver/-/semver-7.8.1.tgz";
    hash = "sha512-rkVq3IXh+4FDGch+KwzX3aV9W3kO54GyEgpvBzSyctDA6Xtd7RJQV1xmXbeQp5v7+VzLOfVqiutSE6GICgPFvg==";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
  };
  "signal-exit@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
    hash = "sha512-bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
  };
  "slash@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/slash/-/slash-3.0.0.tgz";
    hash = "sha512-g9Q1haeby36OSStwb4ntCGGGaKsaVSjQ68fBxoQcutl5fS1vuY18H3wSt3jFyFtrkx+Kz0V1G85A4MyAdDMi2Q==";
  };
  "slash@5.1.0" = fetchurl {
    url = "https://registry.npmjs.org/slash/-/slash-5.1.0.tgz";
    hash = "sha512-ZA6oR3T/pEyuqwMgAKT0/hAv8oAXckzbkmR0UkUosQ+Mc4RxGoJkRmwHgHufaenlyAgE1Mxgpdcrf75y6XcnDg==";
  };
  "smol-toml@1.7.0" = fetchurl {
    url = "https://registry.npmjs.org/smol-toml/-/smol-toml-1.7.0.tgz";
    hash = "sha512-aqVvWoyO21L23mb+drl4RmMXbf6N7FdHjAhTRA9ZBL7apWBgfWC16KjrASI+1p9GAroljyMHj6fK67i0UiTNvQ==";
  };
  "spawndamnit@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/spawndamnit/-/spawndamnit-3.0.1.tgz";
    hash = "sha512-MmnduQUuHCoFckZoWnXsTg7JaiLBJrKFj9UI2MbRPGaJeVpsLcVBu6P/IGZovziM/YBsellCmsprgNA+w0CzVg==";
  };
  "sprintf-js@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
    hash = "sha512-D9cPgkvLlV3t3IzL0D0YLvGA9Ahk4PcvVwUbN0dSGr1aP0Nrt4AEnTUbuGvquEC0mA64Gqt1fzirlRs5ibXx8g==";
  };
  "string-width@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
    hash = "sha512-tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
  };
  "string-width@8.2.1" = fetchurl {
    url = "https://registry.npmjs.org/string-width/-/string-width-8.2.1.tgz";
    hash = "sha512-IIaP0g3iy9Cyy18w3M9YcaDudujEAVHKt3a3QJg1+sr/oX96TbaGUubG0hJyCjCBThFH+tFpcIyoUHUn1ogaLA==";
  };
  "strip-ansi@6.0.1" = fetchurl {
    url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
    hash = "sha512-Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
  };
  "strip-ansi@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.2.0.tgz";
    hash = "sha512-yDPMNjp4WyfYBkHnjIRLfca1i6KMyGCtsVgoKe/z1+6vukgaENdgGBZt+ZmKPc4gavvEZ5OgHfHdrazhgNyG7w==";
  };
  "strip-bom@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
    hash = "sha512-vavAMRXOgBVNF6nyEEmL3DBK19iRpDcoIwW+swQ+CbGiu7lju6t+JklA1MHweoWtadgt4ISVUsXLyDq34ddcwA==";
  };
  "tagged-tag@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/tagged-tag/-/tagged-tag-1.0.0.tgz";
    hash = "sha512-yEFYrVhod+hdNyx7g5Bnkkb0G6si8HJurOoOEgC8B/O0uXLHlaey/65KRv6cuWBNhBgHKAROVpc7QyYqE5gFng==";
  };
  "tar@7.5.16" = fetchurl {
    url = "https://registry.npmjs.org/tar/-/tar-7.5.16.tgz";
    hash = "sha512-56adEpPMouktRlBLXiaYFFzZ/3+JXa8P9n7WbR+ibIjtviN55mEaOkiysCnPnWm+7kkui1Dn8J9l+g6zV8731w==";
  };
  "term-size@2.2.1" = fetchurl {
    url = "https://registry.npmjs.org/term-size/-/term-size-2.2.1.tgz";
    hash = "sha512-wK0Ri4fOGjv/XPy8SBHZChl8CM7uMc5VML7SqiQ0zG7+J5Vr+RMQDoHa2CNT6KHUnTGIXH34UDMkPzAUyapBZg==";
  };
  "tinyexec@1.2.2" = fetchurl {
    url = "https://registry.npmjs.org/tinyexec/-/tinyexec-1.2.2.tgz";
    hash = "sha512-M/Q0B2cp4K7kynaT/vnED1j8TlLY+Pp7C6Wl2bl/7u/F0mUVwdyOpwomQb8JpYLitHUssAJRmLZdMCGsrx7i+g==";
  };
  "tinyglobby@0.2.17" = fetchurl {
    url = "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.17.tgz";
    hash = "sha512-wXR/dYpcqKmfWpEdZjiKJOwCNFndD0DMnrW/cYjVGttEkBfVgcLFHoNrlj47mjOVic9yyNu65alsgF4NQyTa2g==";
  };
  "tinypool@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/tinypool/-/tinypool-2.1.0.tgz";
    hash = "sha512-Pugqs6M0m7Lv1I7FtxN4aoyToKg1C4tu+/381vH35y8oENM/Ai7f7C4StcoK4/+BSw9ebcS8jRiVrORFKCALLw==";
  };
  "to-regex-range@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
    hash = "sha512-65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
  };
  "ts-pattern@5.9.0" = fetchurl {
    url = "https://registry.npmjs.org/ts-pattern/-/ts-pattern-5.9.0.tgz";
    hash = "sha512-6s5V71mX8qBUmlgbrfL33xDUwO0fq48rxAu2LBE11WBeGdpCPOsXksQbZJHvHwhrd3QjUusd3mAOM5Gg0mFBLg==";
  };
  "turbo@2.9.18" = fetchurl {
    url = "https://registry.npmjs.org/turbo/-/turbo-2.9.18.tgz";
    hash = "sha512-bwabv6PupzeavybzEoArBAkwq5fnzwf8OFnRtpHwnviFWuwJPFxtyH+aVp36TmIqK3aYYgtTJ3J0m2ysxxSzQg==";
  };
  "type-fest@5.7.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-5.7.0.tgz";
    hash = "sha512-1URUxUqfHFM1c+zfSPsa3gnkO7Aq21qyH75SIduNYz4SzY964rn1X2vCMQaHSHhktiw+0kPa2iyb6PUpXqB6Vg==";
  };
  "typescript@6.0.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-6.0.3.tgz";
    hash = "sha512-y2TvuxSZPDyQakkFRPZHKFm+KKVqIisdg9/CZwm9ftvKXLP8NRWj38/ODjNbr43SsoXqNuAisEf1GdCxqWcdBw==";
  };
  "uc.micro@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/uc.micro/-/uc.micro-2.1.0.tgz";
    hash = "sha512-ARDJmphmdvUk6Glw7y9DQ2bFkKBHwQHLi2lsaH6PPmz/Ka9sFOBsBluozhDltWmnv9u/cF6Rt87znRTPV+yp/A==";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
  };
  "undici-types@7.19.2" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.19.2.tgz";
    hash = "sha512-qYVnV5OEm2AW8cJMCpdV20CDyaN3g0AjDlOGf1OW4iaDEx8MwdtChUp4zu4H0VP3nDRF/8RKWH+IPp9uW0YGZg==";
  };
  "unicorn-magic@0.4.0" = fetchurl {
    url = "https://registry.npmjs.org/unicorn-magic/-/unicorn-magic-0.4.0.tgz";
    hash = "sha512-wH590V9VNgYH9g3lH9wWjTrUoKsjLF6sGLjhR4sH1LWpLmCOH0Zf7PukhDA8BiS7KHe4oPNkcTHqYkj7SOGUOw==";
  };
  "universalify@0.1.2" = fetchurl {
    url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
    hash = "sha512-rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "wrap-ansi@9.0.2" = fetchurl {
    url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-9.0.2.tgz";
    hash = "sha512-42AtmgqjV+X1VpdOfyTGOYRi0/zsoLqtXQckTmqTeybT+BDIbM/Guxo7x3pE2vtpr1ok6xRqM9OpBe+Jyoqyww==";
  };
  "y18n@5.0.8" = fetchurl {
    url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
    hash = "sha512-0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
  };
  "yallist@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/yallist/-/yallist-5.0.0.tgz";
    hash = "sha512-YgvUTfwqyc7UXVMrB+SImsVYSmTS8X/tSrtdNZMImM+n7+QTriRXyXim0mBrTXNeqzVF0KWGgHPeiyViFFrNDw==";
  };
  "yaml@2.9.0" = fetchurl {
    url = "https://registry.npmjs.org/yaml/-/yaml-2.9.0.tgz";
    hash = "sha512-2AvhNX3mb8zd6Zy7INTtSpl1F15HW6Wnqj0srWlkKLcpYl/gMIMJiyuGq2KeI2YFxUPjdlB+3Lc10seMLtL4cA==";
  };
  "yargs-parser@22.0.0" = fetchurl {
    url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-22.0.0.tgz";
    hash = "sha512-rwu/ClNdSMpkSrUb+d6BRsSkLUq1fmfsY6TOpYzTwvwkg1/NRG85KBy3kq++A8LKQwX6lsu+aWad+2khvuXrqw==";
  };
  "yargs@18.0.0" = fetchurl {
    url = "https://registry.npmjs.org/yargs/-/yargs-18.0.0.tgz";
    hash = "sha512-4UEqdc2RYGHZc7Doyqkrqiln3p9X2DZVxaGbwhn2pi7MrRagKaOcIKe8L3OxYcbhXLgLFUS3zAYuQjKBQgmuNg==";
  };
  "yauzl@3.4.0" = fetchurl {
    url = "https://registry.npmjs.org/yauzl/-/yauzl-3.4.0.tgz";
    hash = "sha512-jIH9yLR9wqr0wOS0TpBvo/g/2UgZH5qePVbjgRliiF0BYvOZyaBknKsF+x9Iht0O6sqgnB93rCICdOZFecJuDw==";
  };
  "yocto-queue@1.2.2" = fetchurl {
    url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-1.2.2.tgz";
    hash = "sha512-4LCcse/U2MHZ63HAJVE+v71o7yOdIe4cZ70Wpf8D/IyjDKYQLV5GD46B+hSTjJsvV5PztjvHoU580EftxjDZFQ==";
  };
  "zod@4.4.3" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.4.3.tgz";
    hash = "sha512-ytENFjIJFl2UwYglde2jchW2Hwm4GJFLDiSXWdTrJQBIN9Fcyp7n4DhxJEiWNAJMV1/BqWfW/kkg71UDcHJyTQ==";
  };
}