#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"

[[repos.hooks]]
id = "check"
name = "check"
language = "system"
entry = "bun run check"
pass_filenames = false
always_run = true
stages = ["pre-commit", "pre-push"]

[[repos.hooks]]
id = "commitlint"
name = "commitlint"
language = "system"
entry = "bun run commitlint --edit"
pass_filenames = true
always_run = true
stages = ["commit-msg"]
