export { compileToZodSource } from "./compile";
export type { CompileToZodSourceRequest, CompileToZodSourceResult } from "./compile";
export {
  coreDiagnosticCodeSchema,
  createDiagnostic,
  diagnosticCodeSchema,
  diagnosticLocationSchema,
  diagnosticSchema,
  diagnosticSeveritySchema,
  formatZodError,
  jsonPointerSchema,
  pluginDiagnosticCodeSchema,
  sourcePositionSchema,
  sourceSpanSchema,
} from "./diagnostics";
export type {
  CoreDiagnosticCode,
  CreateDiagnosticInput,
  Diagnostic,
  DiagnosticCode,
  DiagnosticLocation,
  DiagnosticLocationInput,
  DiagnosticSeverity,
  JsonPointer,
  PluginDiagnosticCode,
  SourcePosition,
  SourcePositionInput,
  SourceSpan,
  SourceSpanInput,
} from "./diagnostics";
export {
  casePropertyKeyTransformSchema,
  mapPropertiesTransformSchema,
  propertyKeyCaseSchema,
  resolveZodEmissionTransforms,
  zodEmissionTransformSchema,
  zodEmissionTransformsSchema,
} from "./emission-transform-config";
export type {
  ZodCasePropertyKeyTransform,
  ZodEmissionTransform,
  ZodEmissionTransformInput,
  ZodMapPropertiesTransform,
  ZodPropertyKeyCase,
} from "./emission-transform-config";
export { inputDocumentSchema, inputDocumentSourceSchema, parseInputDocument } from "./input";
export type {
  FileInputDocumentSource,
  InlineInputDocumentSource,
  InputDocument,
  InputDocumentInput,
  InputDocumentSource,
  InputPlugin,
  PluginOptionsSchema,
  PreparedInput,
  SourceLocationMap,
  UriInputDocumentSource,
} from "./input";
export { collectResultDiagnostics, err, ok } from "./result";
export type { NonEmptyReadonlyArray, Result, ResultErr, ResultOk } from "./result";
export {
  zodRuntimeProgram,
  zodRuntimeProgramIdSchema,
  zodRuntimeProgramSchema,
} from "./runtime-program";
export type {
  ZodRuntimeProgram,
  ZodRuntimeProgramId,
  ZodRuntimeProgramInput,
} from "./runtime-program";
export { runtimeProgramIntrinsicGlobals } from "./runtime-program-closure";
export {
  buildZodSourceFile,
  declarationExportModeSchema,
  resolveZodSourceOutputOptions,
  typeScriptIdentifierSchema,
  zodSourceOutputOptionsSchema,
} from "./source";
export type {
  DeclarationExportMode,
  ResolvedZodSourceOutputOptions,
  TypeScriptIdentifier,
  ZodSourceFile,
  ZodSourceOutputOptions,
} from "./source";
export { printSourceFile, printSourceFileSync } from "./source-print";
export type { SourceFilePrintOptions } from "./source-print";
export {
  zodHelper,
  zodHelperNames,
  zodHelperReceiver,
  zodHelperRequestSchema,
  zodWrapperNames,
} from "./zod-helpers";
export type {
  ZodCodePointLengthHelperRequest,
  ZodExactMultipleOfHelperRequest,
  ZodHelperName,
  ZodHelperReceiver,
  ZodHelperRequest,
  ZodHelperRequestInput,
  ZodUniqueItemsHelperRequest,
  ZodWrapperName,
} from "./zod-helpers";
export {
  isZodKnownMethodName,
  zodFactoryMetadata,
  zodFactoryNames,
  zodKnownMethodNames,
  zodMethodMetadata,
  zodMethodMetadataFor,
  zodMethodNames,
  zodMethodSpecs,
  zodNoArgumentFactoryNames,
  zodNoArgumentMethodNames,
  zodRequiredMethodName,
} from "./zod-plan-metadata";
export type {
  ZodArgumentFactoryName,
  ZodArgumentKind,
  ZodArgumentMetadata,
  ZodArrayElementKind,
  ZodFactoryMetadata,
  ZodKnownMethodName,
  ZodLiteralArgumentValueType,
  ZodMethodPrintStrategy,
  ZodMethodSpec,
  ZodNoArgumentFactoryName,
  ZodNoArgumentMethodName,
  ZodReceiverRequirement,
} from "./zod-plan-metadata";
export {
  parseZodEmissionModule,
  zodArgumentSchema,
  zodArrayArgument,
  zodCall,
  zodDeclaration,
  zodDeclarationNameHint,
  zodDeclarationNameHintProvenanceSchema,
  zodDeclarationNameHintSchema,
  zodDeclarationSchema,
  zodEmissionModuleSchema,
  zodExpressionArgument,
  zodExpressionSchema,
  zodFactory,
  zodFactoryNameSchema,
  zodHelperArgument,
  zodLiteralArgument,
  zodLiteralValueSchema,
  zodMethodCallSchema,
  zodMethodNameSchema,
  zodModule,
  zodObjectPropertySchema,
  zodObjectShapeArgument,
  zodPlan,
  zodReference,
  zodRuntimeGuard,
  zodSymbol,
  zodSymbolSchema,
  zodWrapper,
} from "./zod-plan";
export type {
  ZodArgument,
  ZodArgumentInput,
  ZodArrayArgument,
  ZodDeclaration,
  ZodDeclarationInput,
  ZodDeclarationNameHint,
  ZodDeclarationNameHintInput,
  ZodDeclarationNameHintProvenance,
  ZodEmissionModule,
  ZodEmissionModuleInput,
  ZodExpressionArgument,
  ZodExpression,
  ZodExpressionInput,
  ZodFactoryArgumentsByName,
  ZodFactoryExpression,
  ZodFactoryExpressionInput,
  ZodFactoryName,
  ZodHelperArgument,
  ZodLiteralArgument,
  ZodLiteralValue,
  ZodMethodArgumentsByName,
  ZodMethodCall,
  ZodMethodCallInput,
  ZodMethodName,
  ZodObjectShapeArgument,
  ZodObjectProperty,
  ZodObjectPropertyInput,
  ZodReferenceExpression,
  ZodReferenceExpressionInput,
  ZodRegexFlags,
  ZodRuntimeGuardExpression,
  ZodRuntimeGuardExpressionInput,
  ZodRuntimeGuardPlacement,
  ZodSymbol,
  ZodWrapperExpression,
  ZodWrapperExpressionInput,
} from "./zod-plan";
export * as ts from "@typescript/native-preview/unstable/ast";
